import { posix } from 'node:path';
import type { UiDefinition, UiFramework } from '../domain/ui.ts';
import { vaultPath, type WriteRequest } from '../domain/file.ts';
import { encodeText } from './documents.ts';
import { componentArtifact } from './ui-renderers.ts';

function modulePath(directory: string, target: string): string {
  const relative = posix.relative(directory, target).replace(/\.tsx?$/, '');
  return relative.startsWith('.') ? relative : `./${relative}`;
}

// Computed keys preserve even keys such as __proto__ as data in emitted JavaScript.
function literal(value: unknown, indent = 0): string {
  if (Array.isArray(value)) return `[${value.map(item => literal(item, indent)).join(', ')}]`;
  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0);
    if (!entries.length) return '{}';
    return `{\n${entries.map(([key, item]) => `${' '.repeat(indent + 2)}${key === '__proto__' ? `[${JSON.stringify(key)}]` : /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key)}: ${literal(item, indent + 2)}`).join(',\n')}\n${' '.repeat(indent)}}`;
  }
  return JSON.stringify(value) ?? 'undefined';
}

const storybookPackages: Record<UiFramework, string> = {
  html: '@storybook/html', htmx: '@storybook/html', vanilla: '@storybook/html',
  react: '@storybook/react', vue: '@storybook/vue3', svelte: '@storybook/svelte', angular: '@storybook/angular',
};

/** Return CSF3 modules; the CLI never executes Storybook extension modules. */
export function renderUiStories(
  definitions: readonly UiDefinition[], framework: UiFramework, componentDirectory: string, storiesDirectory: string,
): WriteRequest[] {
  vaultPath(componentDirectory);
  vaultPath(storiesDirectory);
  return [...definitions].sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0).map(definition => {
    const settings = definition.storybook;
    const artifact = componentArtifact(definition, framework);
    const componentImport = modulePath(storiesDirectory, `${componentDirectory}/${artifact.fileName}`);
    const html = ['html', 'htmx', 'vanilla'].includes(framework);
    const htmlPropsType = 'NonNullable<Parameters<typeof component>[0]>';
    const nativeType = html ? `_Meta<${htmlPropsType}>` : framework === 'angular' ? '_Meta<InstanceType<typeof component>>' : '_Meta<typeof component>';
    const props = Object.entries(definition.props);
    const defaults = Object.fromEntries(props.flatMap(([key, prop]) => {
      if (prop.default !== undefined) return [[key, prop.default]];
      if (prop.required) return [[key, prop.type === 'number' ? 0 : prop.type === 'boolean' ? false : '']];
      return [];
    }));
    const controls = Object.fromEntries(props.map(([key, prop]) => [key, {
      control: prop.type === 'string' ? 'text' : prop.type,
      type: { name: prop.type, required: prop.required ?? false },
      ...(prop.description ? { description: prop.description } : {}),
    }]));
    const parameters = settings?.parameters ?? {};
    const docs = parameters.docs !== null && typeof parameters.docs === 'object' && !Array.isArray(parameters.docs) ? parameters.docs : {};
    const descriptions = 'description' in docs && docs.description !== null && typeof docs.description === 'object' && !Array.isArray(docs.description) ? docs.description : {};
    const meta = {
      title: settings?.title ?? `Components/${definition.name ?? definition.id}`,
      tags: settings?.tags ?? ['autodocs'],
      args: { ...defaults, ...settings?.args },
      argTypes: { ...controls, ...settings?.argTypes },
      parameters: { ...parameters, docs: { ...docs, description: { component: definition.description, ...descriptions } } },
    };
    const extension = settings?.extension;
    if (extension) vaultPath(extension);
    const lines = [
      '// Generated by Forge from Markdown. Edit the definition or its Storybook extension module.',
      `import type { Meta as _Meta, StoryObj as _StoryObj } from ${JSON.stringify(storybookPackages[framework])};`,
      `import ${artifact.namedExport ? `{ ${artifact.exportName} as component }` : 'component'} from ${JSON.stringify(componentImport)};`,
      ...(extension ? [
        `import * as storyExtensions from ${JSON.stringify(modulePath(storiesDirectory, extension))};`,
        '',
        `const extensions = storyExtensions as { meta?: Partial<${nativeType}>; stories?: Record<string, _StoryObj> };`,
      ] : []),
      '',
      'const meta = {',
      `${literal(meta).slice(2, -2)},`,
      ...(html ? ['  render: (args) => component(args),'] : ['  component,']),
      ...(extension ? ['  ...extensions.meta,'] : []),
      `} satisfies ${nativeType};`,
      '',
      'export default meta;',
      `type _Story = ${html ? `_StoryObj<${htmlPropsType}>` : framework === 'angular' ? '_StoryObj<InstanceType<typeof component>>' : '_StoryObj<typeof meta>'};`,
    ];
    for (const story of settings?.stories?.length ? settings.stories : [{ name: 'Default' }]) {
      const { name, ...fields } = story;
      lines.push('', `export const ${name}: _Story = {`,
        ...(Object.keys(fields).length ? [`${literal(fields).slice(2, -2)},`] : []),
        ...(extension ? [`  ...extensions.stories?.[${JSON.stringify(name)}],`] : []), '} satisfies _Story;');
    }
    return { path: `${storiesDirectory}/${definition.id}.stories.ts`, bytes: encodeText(lines.join('\n') + '\n') };
  });
}
