// Generated by Forge from Markdown. Edit the definition or its Storybook extension module.
import type { Meta as _Meta, StoryObj as _StoryObj } from "@storybook/html";
import component from "../components/page.js";

const meta = {
  argTypes: {},
  args: {},
  parameters: {
    docs: {
      description: {
        component: "# page\n\nSemantic div boilerplate. Supply child content and application behavior in your project.\n"
      }
    }
  },
  tags: ["autodocs"],
  title: "Components/page",
  render: (args) => component(args),
} satisfies _Meta<NonNullable<Parameters<typeof component>[0]>>;

export default meta;
type _Story = _StoryObj<NonNullable<Parameters<typeof component>[0]>>;

export const Default: _Story = {
} satisfies _Story;
