import { committedEvents } from '../support/events.ts';
import { beforeEach, describe, expect, it } from 'vitest';
import { mkdir, mkdtemp, readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { portableCli } from '../support/portable-cli.ts';

const fixture = portableCli();
let root: string;
beforeEach(async () => { root = await mkdtemp(join(fixture.project, 'locale-')); });
const cli = (args: string[]) => fixture.cli(args, undefined, { root });
async function configure(config: unknown) {
  await mkdir(join(root, 'bin'), { recursive: true });
  await writeFile(join(root, 'bin/config.json'), JSON.stringify(config));
}

describe('localized portable CLI', () => {
  it('uses configured language and invocation overrides without changing saved configuration', async () => {
    await configure({ settings: { language: 'de' } });
    const original = await readFile(join(root, 'bin/config.json'), 'utf8');
    expect(cli(['help', 'read']).body.data.description).toContain('SHA-256-Revision');
    for (const args of [['--lang', 'en', 'help', 'read'], ['help', 'read', '--lang', 'en']]) {
      const result = cli(args);
      expect(result.status).toBe(0);
      expect(result.body.data.description).toContain('Read a document');
      expect(result.body.data.id).toBe('read');
    }
    expect(cli(['config', '--lang', 'en']).body.data.config.settings.language).toBe('en');
    expect(await readFile(join(root, 'bin/config.json'), 'utf8')).toBe(original);
  });

  it('keeps capability IDs, options and usage stable while translating built-in descriptions', () => {
    const english = cli(['schema', '--lang', 'en']), german = cli(['--lang', 'de', 'schema']);
    expect(german.status).toBe(0);
    expect(Object.keys(german.body)).toEqual(Object.keys(english.body));
    const contracts = (commands: Array<{ id: string; usage: string; options: unknown }>) => commands.map(({ id, usage, options }) => ({ id, usage, options }));
    expect(contracts(german.body.data.commands)).toEqual(contracts(english.body.data.commands));
    expect(german.body.data.globalOptions).toEqual(english.body.data.globalOptions);
    expect(german.body.data.commands.find((command: { id: string }) => command.id === 'read').description).not.toBe(english.body.data.commands.find((command: { id: string }) => command.id === 'read').description);
    expect(cli(['make', '--lang', 'de']).body.data.generators.find((generator: { id: string }) => generator.id === 'ui').description).toContain('Markdown');
  });

  it('initializes the requested preference and diagnoses invalid configuration without bypassing it', async () => {
    const setup = cli(['setup', '--lang', 'de']);
    expect(setup.status).toBe(0);
    expect(JSON.parse(await readFile(join(root, 'bin/config.json'), 'utf8')).settings.language).toBe('de');
    const original = await readFile(join(root, 'bin/config.json'), 'utf8');
    expect(cli(['setup', '--lang', 'en']).status).toBe(0);
    expect(await readFile(join(root, 'bin/config.json'), 'utf8')).toBe(original);
    await configure({ settings: { language: 'fr' } });
    const invalid = cli(['--lang', 'de', 'config']);
    expect(invalid.status).toBe(2);
    expect(invalid.body.error.code).toBe('INVALID_CONFIG');
    expect(invalid.body.error.message).toContain('Konfiguration');
    expect(invalid.body.error.details.localization.originalMessage).toContain('settings.language');
  });

  it('preserves exit codes and structured diagnostics when localizing failures', async () => {
    await configure({ settings: { language: 'de' } });
    const german = cli(['read', 'missing.md']), english = cli(['read', 'missing.md', '--lang', 'en']);
    expect(german.status).toBe(3); expect(english.status).toBe(3);
    expect(german.body.error.code).toBe(english.body.error.code);
    expect(german.body.error.message).toContain('nicht gefunden');
    expect(german.body.error.hint).toContain('project current'); expect(english.body.error.hint).toContain('project current');
    expect(german.body.error.details.localization.originalMessage).toBe(english.body.error.message);
    expect(committedEvents(german.body.events)).toEqual([]);
    for (const args of [['--lang', 'fr', 'help'], ['help', '--lang', 'fr'], ['--lang', 'en', 'help', '--lang', 'de']]) {
      const result = cli(args);
      expect(result.status).toBe(2);
      expect(result.body.error.code).toBe(args.includes('fr') ? 'INVALID_LANGUAGE' : 'DUPLICATE_OPTION');
      expect(result.body.events).toEqual([]);
    }
    expect(await readdir(root)).toEqual(['bin']);
  });

  it('leaves user content and generated bytes unchanged across languages', async () => {
    await configure({ settings: { language: 'de' } });
    const literal = '--lang';
    expect(cli(['create', 'literal.md', '--content', literal]).status).toBe(0);
    expect(await readFile(join(root, 'literal.md'), 'utf8')).toBe(literal);
    const content = '# Read a document\n\nUnknown command --lang de.\n';
    await writeFile(join(root, 'user.md'), content);
    const english = cli(['read', 'user.md', '--lang', 'en']), german = cli(['read', 'user.md', '--lang', 'de']);
    expect(german.body.data).toEqual(english.body.data);
    const args = ['make', 'entity', 'Example', '--dry-run'];
    expect(cli([...args, '--lang', 'de']).body.data).toEqual(cli([...args, '--lang', 'en']).body.data);
    expect(cli(['config']).body.data.config.settings.language).toBe('de');
  });

  it('preserves plugin descriptions, results, events and warnings', async () => {
    await configure({ settings: { language: 'de' }, plugins: { enabled: ['quality'] } });
    await mkdir(join(root, 'bin/plugins/quality'), { recursive: true });
    await writeFile(join(root, 'bin/plugins/quality/manifest.json'), JSON.stringify({ id: 'quality', name: 'Quality', version: '1.0.0', minAppVersion: '0.1.0', description: 'Read a document', author: 'Tests' }));
    await writeFile(join(root, 'bin/plugins/quality/main.mjs'), `export default {
      events: [{ id: 'quality.checked', validate: value => typeof value === 'string' }],
      commands: [{ id: 'quality.check', description: 'Read a document', usage: 'quality.check', async run(args, flags, context) {
        await context.events.emit('quality.checked', 'Unknown command'); context.events.warn('Read a document');
        return { message: 'Read a document', generators: [{ id: 'ui', description: 'User content' }] };
      } }]
    };`);
    const english = cli(['quality.check', '--lang', 'en']), german = cli(['quality.check', '--lang', 'de']);
    expect(german.status).toBe(0); expect(german.body).toEqual(english.body);
    expect(cli(['help', 'quality.check']).body.data.description).toBe('Read a document');
  });
});
