/** Stable application codes select human guidance; original diagnostics remain separate. */
export const germanErrors = {
  AMBIGUOUS_BASE_LINK: 'Ein interner Link verweist auf mehrere mögliche Dateien. Prüfen Sie Quellpfad und Linkziel.',
  BASE_CONTEXT_NOT_FOUND: 'Die Kontextdatei ist nicht im Tresorindex enthalten. Prüfen Sie --context.',
  BASE_EVALUATION_ERROR: 'Ein Bases-Ausdruck konnte nicht ausgewertet werden. Prüfen Sie Ansicht, Datei und Diagnose.',
  BASE_VIEW_NOT_FOUND: 'Die angegebene Bases-Ansicht fehlt. Prüfen Sie bases inspect und --view.',
  INVALID_BASE_EXPRESSION: 'Der Bases-Ausdruck ist ungültig. Prüfen Sie die Ausdrucksdiagnose.',
  INVALID_BASE_PROPERTY_TYPES: 'Die Obsidian-Eigenschaftstypen sind ungültig. Prüfen Sie .obsidian/types.json.',
  UNSUPPORTED_BASE_PROPERTY_TYPE: 'Dieser Obsidian-Eigenschaftstyp wird nicht unterstützt. Prüfen Sie die Diagnose.',
  CLAUDE_COMMAND_FAILED: 'Claude Code konnte nicht erfolgreich gestartet oder ausgeführt werden. Prüfen Sie die Diagnose.',
  CLAUDE_COMMAND_TIMEOUT: 'Der Claude-Code-Befehl hat sein Zeitlimit überschritten. Prüfen Sie den Installationszustand vor einer Wiederholung.',
  CLAUDE_NOT_INSTALLED: 'Claude Code wurde nicht gefunden. Installieren Sie die CLI oder geben Sie --claude-bin an.',
  CLAUDE_OUTPUT_LIMIT: 'Die Claude-Code-Ausgabe hat das Größenlimit überschritten. Prüfen Sie den Vorgang vor einer Wiederholung.',
  CLAUDE_WORKING_DIRECTORY_UNAVAILABLE: 'Das Arbeitsverzeichnis für Claude Code ist nicht verfügbar.',
  INVALID_CLAUDE_ARGUMENT: 'Ein Claude-Code-Argument ist ungültig. Prüfen Sie die Diagnose und den Befehlsvertrag.',
  INVALID_CLAUDE_COMMAND: 'Dieser Claude-Code-Befehl wird nicht unterstützt. Prüfen Sie claude capabilities.',
  INVALID_CLAUDE_EXECUTABLE: 'Der Pfad zur Claude-Code-CLI ist ungültig. Prüfen Sie --claude-bin.',
  INVALID_CLAUDE_INPUT: 'Die Claude-Code-Eingabe ist ungültig oder überschreitet das Größenlimit.',
  INVALID_CLAUDE_OPTION: 'Diese Option ist für den Claude-Code-Befehl nicht zulässig. Prüfen Sie die Diagnose.',
  INVALID_CLAUDE_OUTPUT_LIMIT: 'Das Ausgabelimit für Claude Code ist ungültig.',
  INVALID_CLAUDE_SCOPE: 'Der Claude-Code-Geltungsbereich ist ungültig. Prüfen Sie --scope.',
  INVALID_CLAUDE_TIMEOUT: 'Das Zeitlimit für Claude Code ist ungültig.',
  INVALID_BASE_QUERY: 'Die Bases-Abfrage ist ungültig. Prüfen Sie Ansicht, Kontext, Ausdrücke und Diagnose.',
  BASE_INDEX_ERROR: 'Eine Tresordatei konnte nicht indexiert werden. Prüfen Sie Dateipfad und Diagnose.',
  INVALID_CLAUDE_AGENT: 'Die Claude-Agentendefinition ist ungültig. Prüfen Sie Metadaten, Fähigkeiten und Diagnose.',
  INVALID_CLAUDE_HOOKS: 'Die Claude-Hook-Konfiguration ist ungültig. Prüfen Sie Ereignisse, Handler und Diagnose.',
  INVALID_CLAUDE_PLUGIN: 'Das Claude-Plugin-Manifest oder eine Plugin-Datei ist ungültig. Prüfen Sie die Diagnose.',
  INVALID_CLAUDE_SETTINGS: 'Die Claude-Einstellungen sind ungültig. Prüfen Sie die JSON-Struktur und Diagnose.',
  CLAUDE_RUNTIME_FAILED: 'Der Claude-Code-Befehl ist fehlgeschlagen. Prüfen Sie Ausgabe und Installationszustand vor einer Wiederholung.',
  AMBIGUOUS_EDIT: 'Der Suchtext muss genau einmal vorkommen; überlappende Treffer zählen mit.',
  CONFLICT: 'Die Datei existiert bereits oder wurde geändert. Lesen Sie die aktuelle Revision erneut; prüfen Sie generierte Änderungen mit --plan, bevor Sie sie mit --revisions-from übernehmen.',
  CYCLIC_UI_COMPONENT: 'Die Komponenten enthalten einen Zyklus. Entfernen Sie die zyklische Referenz.',
  DATA_SOURCE_RENDERER_UNAVAILABLE: 'Für diese Datenquelle ist kein Generator verfügbar.',
  DUPLICATE_DATA_SOURCE: 'Die Datenquellen-ID ist mehrfach vergeben. Verwenden Sie eindeutige IDs.',
  DUPLICATE_INTERACTION: 'Die Interaktions-ID ist mehrfach vergeben. Verwenden Sie eindeutige IDs.',
  DUPLICATE_EVENT: 'Die Ereignis-ID ist bereits registriert.',
  DUPLICATE_OPTION: 'Eine Option wurde mehrfach oder widersprüchlich angegeben.',
  DUPLICATE_OR_INVALID_ID: 'Eine ID ist ungültig oder bereits vergeben.',
  DUPLICATE_PLUGIN: 'Das Plugin ist bereits registriert.',
  DUPLICATE_UI_COMPONENT: 'Die Komponenten-ID ist mehrfach vergeben. Verwenden Sie eindeutige IDs.',
  EMPTY_DATA_SOURCE_LIBRARY: 'Die Datenquellenbibliothek ist leer. Führen Sie data-sources init aus oder fügen Sie eine Definition hinzu.',
  EMPTY_INTERACTION_LIBRARY: 'Die Interaktionsbibliothek ist leer. Führen Sie interactions init aus oder fügen Sie eine Definition hinzu.',
  EMPTY_UI_LIBRARY: 'Die Komponentenbibliothek ist leer. Führen Sie components init aus oder fügen Sie eine Definition hinzu.',
  EVENT_RECURSION: 'Die maximale Ereignistiefe wurde überschritten. Prüfen Sie rekursive Ereignisbehandler.',
  INCOMPATIBLE_PLUGIN: 'Das Plugin unterstützt diese API-Version nicht.',
  INPUT_REQUIRED: 'Leiten Sie die erforderliche Eingabe über stdin weiter.',
  INVALID_ARGUMENT: 'Die Argumente sind ungültig. Prüfen Sie die Diagnose und die Hilfe mit help <command>.',
  INVALID_BASE: 'Die Base-Struktur ist ungültig. Prüfen Sie die Definition.',
  INVALID_CANVAS: 'Die Canvas-Struktur ist ungültig. Prüfen Sie Knoten, Kanten und IDs.',
  INVALID_COMPONENT_KIND: 'Der Komponententyp ist ungültig. Verwenden Sie domain oder application.',
  INVALID_CONFIG: 'Die Konfiguration ist ungültig oder nicht lesbar. Prüfen Sie bin/config.json und die Diagnose.',
  INVALID_DATA_SOURCE: 'Die Datenquellendefinition ist ungültig. Prüfen Sie die angegebenen Felder.',
  INVALID_INTERACTION: 'Die Interaktionsdefinition ist ungültig. Prüfen Sie Ereignis, Aktionen und Bindungen.',
  INVALID_INTERACTION_STATE: 'Der Interaktionszustand ist ungültig. Prüfen Sie Zustandstypen, Anfangswerte und Aktionsziele.',
  INVALID_ENCODING: 'Die Eingabekodierung ist ungültig. Verwenden Sie gültiges UTF-8 oder Base64.',
  INVALID_EVENT: 'Die Ereignisdefinition oder der Ereigniszustand ist ungültig.',
  INVALID_EVENT_LISTENER: 'Ein Ereignisbehandler muss eine Funktion sein.',
  INVALID_EVENT_PAYLOAD: 'Die Ereignisdaten entsprechen nicht dem Ereignisvertrag.',
  INVALID_FRONTMATTER: 'Das YAML-Frontmatter ist ungültig. Prüfen Sie die Dokumenteigenschaften.',
  INVALID_GENERATION_PLAN: 'Der Generierungsplan ist ungültig. Prüfen Sie die Ausgabepfade.',
  INVALID_GENERATION_REVISIONS: 'Die Revisionsfreigabe ist ungültig. Verwenden Sie die geprüften SHA-256-Revisionen aus dem Plan.',
  INVALID_INPUT: 'Die Eingabe ist ungültig. Prüfen Sie die Diagnose und die zulässigen Eingabeoptionen.',
  INVALID_JSON: 'Die Eingabe muss gültiges JSON enthalten.',
  INVALID_KEY: 'Der Eigenschaftsschlüssel ist ungültig.',
  INVALID_LANGUAGE: 'Die Sprache wird nicht unterstützt. Verwenden Sie --lang en oder --lang de.',
  INVALID_NAME: 'Der Name ist ungültig. Prüfen Sie die erlaubten Zeichen.',
  INVALID_PATH: 'Der Pfad ist ungültig. Verwenden Sie einen relativen Pfad innerhalb des Arbeitsbereichs.',
  INVALID_PLAN: 'Der Schreibplan ist ungültig. Prüfen Sie doppelte und überlappende Pfade.',
  INVALID_PLUGIN: 'Das Plugin ist ungültig. Prüfen Sie Manifest und Implementierung.',
  INVALID_PLUGIN_CONFIG: 'Die Plugin-Konfiguration ist ungültig. Prüfen Sie die aktivierten Plugin-IDs.',
  INVALID_POINTER: 'Der JSON Pointer ist ungültig oder verweist auf keine passende Position.',
  INVALID_PROJECT: 'Die Projektmetadaten sind ungültig. Prüfen Sie .forge/project.json.',
  INVALID_PROJECT_CONTEXT: 'Die gespeicherte Projektauswahl ist ungültig. Verwenden Sie project open <name> oder project close.',
  INVALID_PROJECT_NAME: 'Der Projektname ist ungültig. Verwenden Sie einen gültigen Projektnamen.',
  INVALID_RESULT: 'Der Befehl lieferte nicht serialisierbare Daten. Prüfen Sie vor einem erneuten Versuch die bereits bestätigten Ereignisse.',
  INVALID_SETUP: 'Die Installation kann nicht abgeschlossen werden. Prüfen Sie die Diagnose.',
  INVALID_TEMPLATE: 'Die Markdown-Vorlage ist ungültig. Prüfen Sie Frontmatter und Platzhalter.',
  INVALID_TEMPLATE_DATE: 'Das Datum oder Datumsformat der Vorlage ist ungültig.',
  INVALID_TEMPLATE_PACK: 'Das Vorlagenpaket ist ungültig. Prüfen Sie IDs und Pfade.',
  INVALID_TEMPLATE_VALUES: 'Die Vorlagenwerte sind ungültig. Prüfen Sie Pflichtfelder und Datentypen.',
  INVALID_UI: 'Die UI-Definition ist ungültig. Prüfen Sie Eigenschaften und Komponentenreferenzen.',
  INVALID_UI_FRAMEWORK: 'Das UI-Ziel ist ungültig. Verwenden Sie html, htmx, vanilla, vue, svelte, react oder angular.',
  INVALID_UI_LIBRARY: 'Die Komponentenbibliothek ist ungültig. Prüfen Sie die Definitionen.',
  INVALID_YAML: 'Das YAML-Dokument ist ungültig. Prüfen Sie die Syntax und Aliase.',
  MISSING_ARGUMENT: 'Ein erforderliches Argument fehlt. Prüfen Sie help <command>.',
  NOT_FOUND: 'Die angegebene Datei wurde nicht gefunden. Prüfen Sie Pfad und Projektkontext.',
  OPERATION_FAILED: 'Der Vorgang ist fehlgeschlagen. Prüfen Sie die ursprüngliche Diagnose.',
  PLUGIN_LIFECYCLE: 'Der Plugin-Lebenszyklus ist ungültig. Prüfen Sie die Plugin-Implementierung.',
  PLUGIN_NAMESPACE: 'Der Plugin-Beitrag liegt außerhalb seines erlaubten Namensraums.',
  PROJECT_EXISTS: 'Das Projekt existiert bereits. Verwenden Sie einen anderen Namen oder öffnen Sie das vorhandene Projekt.',
  PROJECT_NOT_FOUND: 'Das Projekt wurde nicht gefunden. Prüfen Sie project list.',
  PROJECT_REQUIRED: 'Öffnen Sie zuerst mit project open <name> ein Forge-Projekt.',
  ROLLBACK_FAILED: 'Die Wiederherstellung ist fehlgeschlagen. Prüfen Sie die in der Diagnose genannten Dateien vor einem erneuten Versuch.',
  STALE_PROJECT_CONTEXT: 'Das ausgewählte Projekt fehlt, ist ungültig oder sein Verzeichnis stimmt nicht mehr mit der Konfiguration überein. Verwenden Sie project open <name> oder project close.',
  UI_RENDERER_UNAVAILABLE: 'Für dieses UI-Ziel ist kein Generator verfügbar.',
  UNKNOWN_COMMAND: 'Der Befehl ist unbekannt. Verfügbare Befehle finden Sie mit help oder schema.',
  UNKNOWN_DATA_SOURCE: 'Die Datenquelle ist unbekannt. Prüfen Sie data-sources list.',
  UNKNOWN_INTERACTION: 'Die Interaktion ist unbekannt. Prüfen Sie interactions list und die zugeordnete Interaktionsbibliothek.',
  UNKNOWN_EVENT: 'Das Ereignis ist nicht registriert.',
  UNKNOWN_GENERATOR: 'Der Generator ist unbekannt. Verfügbare Generatoren finden Sie mit make.',
  UNKNOWN_OPTION: 'Die Option ist unbekannt. Prüfen Sie help <command>.',
  UNKNOWN_SKILL: 'Der Skill ist unbekannt. Prüfen Sie skills list.',
  UNKNOWN_TEMPLATE_VARIABLE: 'Die Vorlage enthält eine unbekannte Variable. Prüfen Sie templates inspect <template.md>.',
  UNKNOWN_UI_COMPONENT: 'Die Komponente ist unbekannt. Prüfen Sie components list.',
  UNSAFE_PATH: 'Der Pfad ist nicht sicher. Verwenden Sie einen Pfad innerhalb des Arbeitsbereichs ohne symbolische Verknüpfungen.',
  UNSUPPORTED_EDIT: 'Diese Bearbeitung wird für den Dateityp nicht unterstützt. Prüfen Sie help edit, help patch oder help write.',
  WORKSPACE_BUSY: 'Ein anderer Schreibvorgang sperrt den Arbeitsbereich. Versuchen Sie es nach dessen Abschluss erneut.',
  GENERATION_DRIFT: 'Generierte Dateien fehlen oder weichen von den Definitionen ab. Prüfen Sie die Änderungen mit --plan.',
  UI_DRIFT: 'Generierte UI-Dateien fehlen oder weichen von den Definitionen ab. Prüfen Sie die Änderungen mit --plan.',
  DATA_SOURCE_DRIFT: 'Generierte Datenquellendateien fehlen oder weichen von den Definitionen ab. Prüfen Sie die Änderungen mit --plan.',
} satisfies Record<string, string>;
