import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { EventBus } from '../../src/application/plugins/events.ts';
import { registerHostEvents } from '../../src/application/plugins/host-events.ts';
import { ProjectService } from '../../src/application/projects/projects.ts';
import { Workspace } from '../../src/application/workspace/workspace.ts';
import { WorkflowSync } from '../../src/application/workflows/workflows.ts';
import { ObsidianDocuments } from '../../src/infrastructure/documents/codec.ts';
import { NodeEventScope } from '../../src/infrastructure/plugins/event-scope.ts';
import { componentScaffold, projectScaffold } from '../../src/plugins/scaffolds/infrastructure/projects.ts';
import { NodeFiles } from '../../src/infrastructure/workspace/files.ts';
import { yamlWorkflowRenderer } from '../../src/infrastructure/workflows/renderer.ts';
import { committedEvents } from '../support/events.ts';

let root: string;
const check = 'name: app check\non:\n  pull_request:\njobs:\n  check:\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm ci\n';
async function put(path: string, content: string) {
  await mkdir(dirname(join(root, path)), { recursive: true });
  await writeFile(join(root, path), content);
}
async function project(name: string) {
  await put(`src/${name}/.forge/project.json`, JSON.stringify({ schemaVersion: 1, name, type: 'library' }));
}
async function service(dryRun = false) {
  const files = await NodeFiles.at(root), events = new EventBus(new NodeEventScope());
  registerHostEvents(events);
  const workspace = new Workspace(files, new ObsidianDocuments(), events, dryRun, root);
  return { events, sync: new WorkflowSync(workspace, new ProjectService(files, workspace, 'src', () => ({ project: projectScaffold, component: componentScaffold }), events), yamlWorkflowRenderer) };
}
const read = (path: string) => readFile(join(root, path), 'utf8');

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), 'forge-workflows-'));
  await project('app');
  await project('site');
  await put('src/app/src/infrastructure/workflows/check/check.yml', check);
  await put('src/app/src/infrastructure/workflows/guard/workflows.yaml', 'on:\n  pull_request:\n    paths: [/**]\njobs:\n  guard:\n    runs-on: ubuntu-latest\n    steps:\n      - run: node "$GITHUB_WORKSPACE/bin/forge.js" workflows sync --check\n');
  await put('src/site/src/infrastructure/workflows/check/check.yml', check.replace('app check', 'site check'));
  // Not a managed project: no marker, so its workflows are ignored.
  await put('src/loose/src/infrastructure/workflows/check/check.yml', check);
});
afterEach(async () => { await rm(root, { recursive: true, force: true }); });

describe('project-owned workflow synchronization', () => {
  it('lists every managed project workflow with its generated target and status', async () => {
    const { sync } = await service();
    expect(await sync.list()).toEqual({
      directory: '.github/workflows', count: 3, inSync: false,
      workflows: [
        { project: 'app', concern: 'check', source: 'src/app/src/infrastructure/workflows/check/check.yml', target: '.github/workflows/app--check.yml', status: 'missing' },
        { project: 'app', concern: 'guard', source: 'src/app/src/infrastructure/workflows/guard/workflows.yaml', target: '.github/workflows/app--guard--workflows.yml', status: 'missing' },
        { project: 'site', concern: 'check', source: 'src/site/src/infrastructure/workflows/check/check.yml', target: '.github/workflows/site--check.yml', status: 'missing' },
      ],
    });
  });

  it('previews without writing, then writes scoped copies with committed events, then reports no drift', async () => {
    const preview = await (await service(true)).sync.sync();
    expect(preview.dryRun).toBe(true);
    expect(preview.changes.map(change => [change.path, change.operation])).toEqual([
      ['.github/workflows/app--check.yml', 'created'], ['.github/workflows/app--guard--workflows.yml', 'created'], ['.github/workflows/site--check.yml', 'created'],
    ]);
    expect(preview.changes[0]).toMatchObject({ diff: expect.stringContaining('+    working-directory: src/app') });
    await expect(read('.github/workflows/app--check.yml')).rejects.toMatchObject({ code: 'ENOENT' });

    const { sync, events } = await service();
    const written = await sync.sync();
    expect(written.workflows.every(entry => entry.status === 'missing')).toBe(true);
    expect(committedEvents(events.history).map(event => (event.payload as { path: string }).path)).toEqual([
      '.github', '.github/workflows', '.github/workflows/app--check.yml', '.github/workflows/app--guard--workflows.yml', '.github/workflows/site--check.yml',
    ]);
    const app = await read('.github/workflows/app--check.yml');
    expect(app).toMatch(/^# Generated by forge workflows sync from src\/app\/src\/infrastructure\/workflows\/check\/check\.yml\./);
    expect(app).toContain('    paths:\n      - src/app/**\n      - .github/workflows/app--check.yml');
    expect(await read('.github/workflows/app--guard--workflows.yml')).toContain('    paths:\n      - "**"\n      - .github/workflows/app--guard--workflows.yml\n');
    expect(await sync.check()).toMatchObject({ check: true, inSync: true, count: 3 });
    expect((await sync.sync()).changes).toEqual([]);
  });

  it('reports changed, missing and stale generated files as WORKFLOW_DRIFT and repairs them', async () => {
    const { sync } = await service();
    await sync.sync();
    await put('src/app/src/infrastructure/workflows/check/check.yml', check.replace('npm ci', 'npm ci --ignore-scripts'));
    await rm(join(root, '.github/workflows/site--check.yml'));
    await rm(join(root, 'src/app/src/infrastructure/workflows/guard'), { recursive: true });
    await put('.github/workflows/hand-written.yml', 'on: push\njobs: {}\n');
    await expect(sync.check()).rejects.toMatchObject({ code: 'WORKFLOW_DRIFT', exitCode: 5, details: { workflows: [
      { project: 'app', concern: 'check', source: 'src/app/src/infrastructure/workflows/check/check.yml', target: '.github/workflows/app--check.yml', status: 'changed' },
      { project: null, concern: null, source: null, target: '.github/workflows/app--guard--workflows.yml', status: 'stale' },
      { project: 'site', concern: 'check', source: 'src/site/src/infrastructure/workflows/check/check.yml', target: '.github/workflows/site--check.yml', status: 'missing' },
    ] } });
    const repaired = await sync.sync();
    expect(repaired.changes.map(change => [change.path, change.operation])).toEqual([
      ['.github/workflows/app--check.yml', 'updated'], ['.github/workflows/site--check.yml', 'created'], ['.github/workflows/app--guard--workflows.yml', 'deleted'],
    ]);
    expect(await read('.github/workflows/app--check.yml')).toContain('npm ci --ignore-scripts');
    await expect(read('.github/workflows/app--guard--workflows.yml')).rejects.toMatchObject({ code: 'ENOENT' });
    expect(await read('.github/workflows/hand-written.yml')).toBe('on: push\njobs: {}\n');
    expect((await sync.check()).inSync).toBe(true);
  });

  it('never overwrites a hand-written file at a generated path', async () => {
    await put('.github/workflows/app--check.yml', 'name: hand written\n');
    const { sync } = await service();
    await expect(sync.sync()).rejects.toMatchObject({ code: 'CONFLICT', details: { path: '.github/workflows/app--check.yml' } });
    expect(await read('.github/workflows/app--check.yml')).toBe('name: hand written\n');
  });

  it('rejects an invalid authored workflow without writing any entrypoint', async () => {
    await put('src/site/src/infrastructure/workflows/check/check.yml', 'on: [push\n');
    const { sync } = await service();
    await expect(sync.sync()).rejects.toMatchObject({ code: 'INVALID_WORKFLOW', message: expect.stringContaining('src/site/src/infrastructure/workflows/check/check.yml') });
    await expect(read('.github/workflows/app--check.yml')).rejects.toMatchObject({ code: 'ENOENT' });
  });
});
