import { beforeAll, describe, expect, it } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { portableCli } from '../support/portable-cli.ts';
import { committedEvents } from '../support/events.ts';
import { workspaceRoot } from '../support/workspace.ts';

const environment = portableCli();
const cli = (args: string[]) => environment.cli(args);
const source = 'src/shop/src/infrastructure/workflows/check/check.yml';
const target = '.github/workflows/shop--check.yml';
const authored = 'name: shop check\non:\n  push:\n    branches: [main]\n  pull_request:\njobs:\n  check:\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm ci\n';

beforeAll(async () => {
  await mkdir(join(environment.project, 'bin'), { recursive: true });
  await writeFile(join(environment.project, 'bin/config.json'), JSON.stringify({ schemaVersion: 1, paths: { projects: 'src' } }));
  expect(cli(['write', 'src/shop/.forge/project.json', '--content', JSON.stringify({ schemaVersion: 1, name: 'shop', type: 'library' })]).status).toBe(0);
  expect(cli(['write', source, '--content', authored]).status).toBe(0);
  // A selected project must not redirect workspace-scoped synchronization.
  expect(cli(['project', 'open', 'shop']).status).toBe(0);
});

describe('workflows command family', () => {
  it('discovers, previews, synchronizes and checks generated entrypoints at the workspace root', async () => {
    const listed = cli(['workflows']);
    expect(listed.status).toBe(0);
    expect(listed.body.context).toMatchObject({ root: environment.project, project: null });
    expect(listed.body.data).toMatchObject({ count: 1, inSync: false, workflows: [{ project: 'shop', concern: 'check', source, target, status: 'missing' }] });

    const missing = cli(['workflows', 'sync', '--check']);
    expect(missing.status).toBe(5);
    expect(missing.body.error).toMatchObject({ code: 'WORKFLOW_DRIFT', retryable: false, details: { workflows: [{ target, status: 'missing' }] } });

    const preview = cli(['workflows', 'sync', '--dry-run']);
    expect(preview.status).toBe(0);
    expect(preview.body.data).toMatchObject({ dryRun: true, changes: [{ path: target, operation: 'created', diff: expect.stringContaining('+      - src/shop/**') }] });
    expect(committedEvents(preview.body.events)).toEqual([]);
    await expect(readFile(join(environment.project, target))).rejects.toMatchObject({ code: 'ENOENT' });

    const synced = cli(['workflows', 'sync']);
    expect(synced.status).toBe(0);
    expect(committedEvents(synced.body.events)).toEqual([
      { id: 'vault.create', payload: { path: '.github', kind: 'folder', operation: 'created' } },
      { id: 'vault.create', payload: { path: '.github/workflows', kind: 'folder', operation: 'created' } },
      expect.objectContaining({ id: 'vault.create', payload: expect.objectContaining({ path: target, kind: 'file' }) }),
    ]);
    const generated = await readFile(join(environment.project, target), 'utf8');
    expect(generated).toContain(`# Generated by forge workflows sync from ${source}.`);
    expect(generated).toContain('defaults:\n  run:\n    working-directory: src/shop\n');
    expect(cli(['workflows', 'sync', '--check']).body.data).toMatchObject({ check: true, inSync: true, count: 1 });
  });

  it('reports drift after the authored source changes, in the requested language', () => {
    // File commands follow the selected project, so the authored source is project-relative here.
    const projectSource = 'src/infrastructure/workflows/check/check.yml';
    expect(cli(['write', projectSource, '--content', authored.replace('npm ci', 'npm test'), '--if-match', cli(['read', projectSource]).body.data.revision]).status).toBe(0);
    const drift = cli(['--lang', 'de', 'workflows', 'sync', '--check']);
    expect(drift.status).toBe(5);
    expect(drift.body.error).toMatchObject({ code: 'WORKFLOW_DRIFT', message: 'Generierte GitHub-Workflows fehlen, weichen ab oder sind veraltet.', details: { workflows: [{ target, status: 'changed' }] } });
    expect(cli(['workflows', 'sync']).body.data.changes).toEqual([expect.objectContaining({ path: target, operation: 'updated' })]);
    expect(cli(['workflows', 'sync', '--check']).status).toBe(0);
  });

  it('keeps this workspace\'s generated GitHub workflows in sync with every project\'s authored workflows', () => {
    const result = spawnSync(process.execPath, [join(workspaceRoot, 'bin/app.js'), '--json', 'workflows', 'sync', '--check'], { cwd: workspaceRoot, encoding: 'utf8', timeout: 30_000 });
    expect(result.stderr).toBe('');
    const body = JSON.parse(result.stdout);
    expect(body.error).toBeUndefined();
    expect(body.data.workflows.map((entry: { target: string }) => entry.target)).toEqual(expect.arrayContaining([
      '.github/workflows/forge-showcase--check.yml', '.github/workflows/the-forge--check.yml', '.github/workflows/the-forge--guard--workflows.yml',
    ]));
    expect(result.status).toBe(0);
  });

  it.each([
    [['workflows', 'list', '--check']],
    [['workflows', 'sync', 'extra']],
    [['workflows', 'remove']],
  ])('rejects invalid usage %j', args => {
    const result = cli(args);
    expect(result.status).toBe(2);
    expect(result.body.error.code).toBe('INVALID_ARGUMENT');
  });
});
