import { describe, expect, it } from 'vitest';
import {
  ensureDistinctTargets, generatedWorkflowPath, isGeneratedWorkflow, projectRelative, scopedPattern, scopedTriggerPaths, workflowSource,
} from '../../src/domain/workflows/workflow.ts';
import { yamlWorkflowRenderer } from '../../src/infrastructure/workflows/renderer.ts';

const encode = (text: string) => new TextEncoder().encode(text);
const source = workflowSource('demo', 'src/demo', 'src/demo/src/infrastructure/workflows/check/check.yml')!;
const render = (text: string, from = source) => new TextDecoder().decode(yamlWorkflowRenderer.render(encode(text), from));

describe('workflow sources and generated entrypoints', () => {
  it('discovers only direct YAML files in a project concern folder', () => {
    expect(source).toEqual({ project: 'demo', projectDirectory: 'src/demo', concern: 'check', source: 'src/demo/src/infrastructure/workflows/check/check.yml', target: '.github/workflows/demo--check.yml' });
    expect(workflowSource('demo', 'src/demo', 'src/demo/src/infrastructure/workflows/guard/workflows.yaml')?.target).toBe('.github/workflows/demo--guard--workflows.yml');
    for (const path of ['src/demo/src/infrastructure/workflows/check.yml', 'src/demo/src/infrastructure/workflows/check/nested/check.yml',
      'src/demo/src/infrastructure/workflows/check/notes.md', 'src/other/src/infrastructure/workflows/check/check.yml']) {
      expect(workflowSource('demo', 'src/demo', path), path).toBeUndefined();
    }
    expect(() => workflowSource('demo', 'src/demo', 'src/demo/src/infrastructure/workflows/Check/check.yml')).toThrow(expect.objectContaining({ code: 'INVALID_WORKFLOW' }));
    expect(generatedWorkflowPath('demo', 'release', 'publish')).toBe('.github/workflows/demo--release--publish.yml');
  });

  it('rejects two sources that generate the same entrypoint', () => {
    const yml = workflowSource('demo', 'src/demo', 'src/demo/src/infrastructure/workflows/check/check.yml')!;
    const yaml = workflowSource('demo', 'src/demo', 'src/demo/src/infrastructure/workflows/check/check.yaml')!;
    expect(() => ensureDistinctTargets([yml, yaml])).toThrow(expect.objectContaining({ code: 'INVALID_WORKFLOW' }));
    expect(() => ensureDistinctTargets([yml])).not.toThrow();
  });

  it('scopes path filters to the project, anchors workspace patterns and keeps negation', () => {
    expect(scopedPattern('docs/**', 'src/demo')).toBe('src/demo/docs/**');
    expect(scopedPattern('!docs/**', 'src/demo')).toBe('!src/demo/docs/**');
    expect(scopedPattern('/**', 'src/demo')).toBe('**');
    expect(scopedPattern('/bin/forge.js', 'src/demo')).toBe('bin/forge.js');
    const target = '.github/workflows/demo--check.yml';
    expect(scopedTriggerPaths({}, 'src/demo', target)).toEqual(['src/demo/**', target]);
    expect(scopedTriggerPaths({ paths: ['src/**', '/bin/**'] }, 'src/demo', target)).toEqual(['src/demo/src/**', 'bin/**', target]);
    expect(scopedTriggerPaths({ pathsIgnore: ['docs/**', '!docs/keep.md'] }, 'src/demo', target)).toEqual(['src/demo/**', '!src/demo/docs/**', 'src/demo/docs/keep.md', target]);
  });

  it('resolves authored working directories inside the workspace', () => {
    expect(projectRelative('.', 'src/demo')).toBe('src/demo');
    expect(projectRelative('ui/app', 'src/demo')).toBe('src/demo/ui/app');
    expect(projectRelative('../..', 'src/demo')).toBe('.');
    expect(projectRelative('/tools', 'src/demo')).toBe('tools');
    expect(() => projectRelative('../../..', 'src/demo')).toThrow(expect.objectContaining({ code: 'INVALID_WORKFLOW' }));
  });
});

describe('YAML workflow rendering', () => {
  it('adds a generated header, path filters, the project path and working directory while keeping the rest verbatim', () => {
    const output = render([
      '# Authored next to the project.',
      'name: demo check',
      'on:',
      '  push:',
      '    branches: [main]',
      '  pull_request:',
      '  workflow_dispatch:',
      'permissions:',
      '  contents: read',
      'jobs:',
      '  check:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0',
      "      - run: npm ci",
      '',
    ].join('\n'));
    expect(output).toBe([
      '# Generated by forge workflows sync from src/demo/src/infrastructure/workflows/check/check.yml.',
      '# Do not edit this file; change the source and run: node bin/forge.js workflows sync',
      '',
      '# Authored next to the project.',
      'name: demo check',
      'on:',
      '  push:',
      '    branches: [ main ]',
      '    paths:',
      '      - src/demo/**',
      '      - .github/workflows/demo--check.yml',
      '  pull_request:',
      '    paths:',
      '      - src/demo/**',
      '      - .github/workflows/demo--check.yml',
      '  workflow_dispatch:',
      'permissions:',
      '  contents: read',
      'env:',
      '  FORGE_PROJECT_PATH: src/demo',
      'defaults:',
      '  run:',
      '    working-directory: src/demo',
      'jobs:',
      '  check:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0',
      '      - run: npm ci',
      '',
    ].join('\n'));
    expect(isGeneratedWorkflow(output)).toBe(true);
    expect(render(output.split('\n').slice(3).join('\n'))).not.toBe('');
  });

  it('normalizes event lists, merges existing defaults and scopes job and step working directories', () => {
    const output = render([
      'on: [push, pull_request]',
      'env: { LEVEL: full }',
      'defaults:',
      '  run:',
      '    shell: bash',
      '    working-directory: ui',
      'jobs:',
      '  build:',
      '    runs-on: ubuntu-latest',
      '    defaults: { run: { working-directory: tools } }',
      '    steps:',
      '      - run: node "$GITHUB_WORKSPACE/bin/forge.js" --version',
      '        working-directory: ../..',
      '      - run: ls',
      '        working-directory: ${{ github.workspace }}',
      '',
    ].join('\n'));
    expect(output).toContain('on:\n  push:\n    paths:\n      - src/demo/**\n      - .github/workflows/demo--check.yml\n  pull_request:\n    paths:');
    expect(output).toContain('env: { LEVEL: full, FORGE_PROJECT_PATH: src/demo }');
    expect(output).toContain('defaults:\n  run:\n    shell: bash\n    working-directory: src/demo/ui\n');
    expect(output).toContain('defaults: { run: { working-directory: src/demo/tools } }');
    expect(output).toContain('        working-directory: .\n');
    expect(output).toContain('working-directory: ${{ github.workspace }}');
  });

  it('prefixes declared paths and converts paths-ignore into negated project paths', () => {
    const output = render(['on:', '  pull_request:', "    paths: ['/**']", '  push:', '    paths-ignore: [docs/**]', 'jobs: {}', ''].join('\n'));
    expect(output).toContain('  pull_request:\n    paths:\n      - "**"\n      - .github/workflows/demo--check.yml\n');
    expect(output).toContain('  push:\n    paths:\n      - src/demo/**\n      - "!src/demo/docs/**"\n      - .github/workflows/demo--check.yml');
    expect(output).not.toContain('paths-ignore');
  });

  it('renders identical input to identical bytes', () => {
    const text = 'on: push\njobs:\n  a: { runs-on: ubuntu-latest, steps: [] }\n';
    expect(render(text)).toBe(render(text));
  });

  it.each([
    ['invalid YAML', 'on: [push\njobs: {}\n'],
    ['a non-mapping document', '- push\n'],
    ['a workflow without jobs', 'on: push\n'],
    ['an unsupported trigger shape', 'on: 1\njobs: {}\n'],
    ['non-string path filters', 'on:\n  push:\n    paths: [1]\njobs: {}\n'],
    ['both path filters', 'on:\n  push:\n    paths: [a]\n    paths-ignore: [b]\njobs: {}\n'],
    ['a job that is not a mapping', 'on: push\njobs:\n  a: 1\n'],
    ['a non-string working directory', 'on: push\ndefaults: { run: { working-directory: 1 } }\njobs: {}\n'],
    ['a working directory outside the workspace', 'on: push\njobs:\n  a:\n    steps:\n      - run: ls\n        working-directory: ../../..\n'],
  ])('rejects %s with INVALID_WORKFLOW', (_label, text) => {
    expect(() => render(text)).toThrow(expect.objectContaining({ code: 'INVALID_WORKFLOW' }));
  });

  it('rejects bytes that are not UTF-8', () => {
    expect(() => yamlWorkflowRenderer.render(new Uint8Array([0xff, 0xfe]), source)).toThrow(expect.objectContaining({ code: 'INVALID_WORKFLOW' }));
  });
});
