export const germanCommands = {
  help: 'Befehle und ihre Verwendung ohne interaktive Abfragen entdecken.',
  schema: 'Maschinenlesbarer Katalog der verfügbaren Funktionen.',
  config: 'Die geprüfte wirksame Konfiguration und ihren Quellpfad anzeigen.',
  setup: 'The Forge installieren und fehlende Konfiguration, Skills, Vorlagen und Projektanleitungen anlegen.',
  templates: 'Markdown-Vorlagen und Pflichtfelder entdecken oder das Planungspaket installieren.',
  project: 'TypeScript-Projekte verwalten und getestete Domain- oder Anwendungskomponenten hinzufügen.',
  components: 'Markdown-Komponenten verwalten, prüfen, importieren und exportieren.',
  'data-sources': 'Markdown-Datenquellen verwalten, prüfen, importieren und exportieren.',
  interactions: 'Wiederverwendbare Markdown-Interaktionen für ausführbares UI-Verhalten verwalten.',
  workflows: 'Projekteigene CI-Workflows entdecken und ihre generierten GitHub-Einstiegspunkte synchronisieren; --check meldet Abweichungen.',
  claude: 'Native Claude-Code-Agenten, Hooks und Plugins mit Revisionsschutz und installiertem CLI verwalten.',
  bases: 'Native Obsidian-Bases-Ansichten ohne laufendes Obsidian als Datei-Repositories abfragen.',
  formats: 'Native Obsidian-Formate und unterstützte Vorgänge anzeigen.',
  list: 'Dateien in stabiler Pfadreihenfolge auflisten; symbolische Verknüpfungen, Git und node_modules überspringen.',
  read: 'Ein Dokument, UTF-8-Text oder einen Base64-Anhang mit seiner SHA-256-Revision lesen.',
  validate: 'Markdown-Frontmatter, Canvas-Graphen, Base-Strukturen oder UTF-8-Text prüfen.',
  create: 'Eine Notiz, ein Canvas, eine Base oder eine Datei erstellen. Vorhandene Dateien werden nicht überschrieben.',
  write: 'Eine Datei erstellen oder ersetzen; Ersetzen erfordert die aktuelle Revision.',
  edit: 'Markdown oder UTF-8-Text ergänzen oder genau einen wörtlichen Treffer ersetzen.',
  properties: 'YAML-Frontmatter-Eigenschaften zusammenführen und den Markdown-Inhalt erhalten.',
  patch: 'Einen Canvas-/Base-Wert über JSON Pointer setzen; - hängt an ein vorhandenes Array an.',
  make: 'Code, Planungsdokumente, UI, Storybook-Stories oder Datenquellenadapter mit Testdaten generieren.',
  events: 'Ereignisverträge des Aufrufs auflisten.',
  plugins: 'Explizit geladene Plugin-Manifeste auflisten.',
  skills: 'Mitgelieferte und von Plugins bereitgestellte Agent-Skills auflisten, lesen oder installieren.',
} satisfies Record<string, string>;

export const germanGenerators = {
  form: 'Typisierte Formulardefinition mit Zod-Validierung und HTML-Vorschau in einem Forge-Projekt.',
  entity: 'Domain-Entität mit Identität und Prüfung von Invarianten.',
  'value-object': 'Unveränderliches Wertobjekt mit Gleichheitsprüfung und Validierung.',
  'use-case': 'Anwendungsfall mit injiziertem Repository-Port.',
  event: 'Typisierte Ereignisdaten mit Laufzeitbeschreibung.',
  plugin: 'Installierbarer Plugin-Ordner mit Manifest, Befehlsnamensraum und Lebenszyklus-Hooks.',
  document: 'Obsidian-Markdown-/Frontmatter-Vorlagen mit typisierten Werten rendern.',
  ui: 'Deterministischen UI-Code aus Markdown-Komponentendefinitionen generieren.',
  stories: 'Native Storybook-CSF-Stories für vorhandene UI-Komponenten generieren.',
  'data-source': 'Typisierten REST- oder lokalen JSON-Adapter mit deterministischen Testdaten aus Markdown generieren.',
} satisfies Record<string, string>;

export const germanGuidance = {
  attachments: 'Dateien verlustfrei als Bytes lesen, kopieren, ersetzen und einbetten; keine integrierte Konvertierung, Darstellung oder PDF-Inhaltsbearbeitung.',
  otherFiles: 'Uninterpretierte Bytes; Plugins können weitere Verarbeitung bereitstellen.',
  textFiles: 'UTF-8 lesen, wörtlich bearbeiten, ergänzen und vollständig ersetzen, mit Unified-Diffs im Probelauf; ungültiges UTF-8 wird als Base64-Anhang gelesen.',
  delivery: 'Geordnet, abgewartet und mit separaten Snapshots je Behandler; Fehler werden zu Warnungen. Obsidian-artige vault.*-Ereignisse folgen jedem erfolgreichen Schreibvorgang (zuerst neue Ordner, übergeordnete vor untergeordneten, dann Dateien in Stapelreihenfolge); Probeläufe senden stattdessen workspace.quick-preview. metadataCache.*-Verträge sind für den Kernel-Index reserviert. operation.*-, command.*-, claude.*- und plugin.*-Ereignisse sind Lebenszyklusphasen; workspace.*-Ereignisse entsprechen Obsidians Workspace (file-open, quick-preview, layout-ready, quit, project-change). Host-Namensräume gehören dem Host: Plugins beobachten sie, senden aber nur eigene Ereignisse. onAny beobachtet alle Ereignisse; replay liest den begrenzten Verlauf dieses Aufrufs. Keine dauerhafte Wiederholung. Die Antwort enthält standardmäßig nur vault.*-Ereignisse; --events none|changes|all oder settings.events wählt die Ausgabe, ohne Zustellung oder replay zu ändern.',
  eventChanges: 'Nur erfolgreich geschriebene vault.*-Ereignisse: vault.create, vault.modify, vault.delete und vault.rename für Dateien und Ordner.',
  setup: {
    'node bin/app.js templates list': 'Die installierten, bearbeitbaren Planungsvorlagen entdecken.',
    'node bin/app.js templates inspect workflow/prd.md': 'Planungseingaben vor dem Generieren eines Anforderungsdokuments prüfen.',
    'node bin/app.js project list': 'Ein Projekt suchen und vor dem Generieren von Projektdateien ausdrücklich öffnen.',
  },
};

/** German descriptions of host event contracts; plugin-defined events keep their own descriptions. */
export const germanEvents = {
  'command.started': 'Ein weitergeleiteter Befehl aktiviert gleich Plugins und läuft an.',
  'command.succeeded': 'Ein weitergeleiteter Befehl wurde erfolgreich beendet.',
  'command.failed': 'Ein weitergeleiteter Befehl ist fehlgeschlagen; Fehlercodes enthalten keine Befehlseingaben.',
  'operation.started': 'Ein geschützter Workspace-Vorgang hat begonnen, auch bei Probeläufen.',
  'operation.succeeded': 'Ein geschützter Workspace-Vorgang wurde abgeschlossen, auch bei Probeläufen.',
  'operation.failed': 'Ein geschützter Workspace-Vorgang ist fehlgeschlagen.',
  'claude.started': 'Ein Claude-Aufruf hat mit Prüfung oder Vorschau begonnen.',
  'claude.succeeded': 'Ein Claude-Aufruf oder eine geprüfte Vorschau wurde abgeschlossen.',
  'claude.failed': 'Prüfung, Ausführung oder Ausgabeverarbeitung von Claude ist fehlgeschlagen.',
  'claude.executed': 'Der Claude-Prozess hat einen Exit-Status geliefert, auch einen von null verschiedenen.',
  'vault.create': 'Ein erfolgreicher Schreibvorgang hat eine Datei oder einen Ordner angelegt.',
  'vault.modify': 'Ein erfolgreicher Schreibvorgang hat eine vorhandene Datei ersetzt.',
  'vault.delete': 'Eine Datei oder ein Ordner wurde entfernt; Revision und Bytes einer Datei beschreiben ihren vorherigen Inhalt.',
  'vault.rename': 'Eine Datei oder ein Ordner wurde in einem erfolgreichen Stapel von oldPath nach path verschoben.',
  'metadataCache.changed': 'Eine geschriebene Markdown-Datei wurde indexiert; cache enthält ihre JSON-Metadaten.',
  'metadataCache.deleted': 'Eine gelöschte Datei hat den Index verlassen; prevCache enthält ihre letzten bekannten Metadaten oder null.',
  'metadataCache.resolve': 'Die aufgelösten und nicht aufgelösten Links einer Datei wurden aktualisiert.',
  'metadataCache.resolved': 'Die Linkauflösung für einen geschriebenen Stapel ist abgeschlossen.',
  'workspace.file-open': 'Ein Befehl hat eine Datei über den Workspace-Lesepfad gelesen.',
  'workspace.quick-preview': 'Ein Probelauf hat eine geplante Dateiänderung angezeigt, ohne sie zu schreiben.',
  'workspace.layout-ready': 'Plugins sind aktiv und der Befehl läuft gleich an.',
  'workspace.quit': 'Der Aufruf endet; danach laufen bestmöglich Beendigungsaufgaben, bevor Plugins entladen werden.',
  'workspace.project-change': 'project open oder project close hat eine andere Projektauswahl gespeichert.',
  'plugin.registered': 'Ein Plugin hat die atomare Registrierung seiner Beiträge bestanden.',
  'plugin.activating': 'Ein registriertes Plugin führt gleich seinen Aktivierungs-Hook aus.',
  'plugin.activated': 'Der Aktivierungs-Hook eines Plugins wurde erfolgreich abgeschlossen.',
  'plugin.activation-failed': 'Die Aktivierung eines Plugins ist fehlgeschlagen; die erfasste Bereinigung bleibt geplant.',
  'plugin.unloading': 'Ein gestartetes Plugin gibt gleich seine Ressourcen für diesen Aufruf frei.',
  'plugin.unloaded': 'Die Bereinigung eines Plugins wurde erfolgreich abgeschlossen.',
  'plugin.unload-failed': 'Die Bereinigung eines Plugins ist fehlgeschlagen; die übrige Bereinigung läuft weiter.',
} satisfies Record<string, string>;
