import type { ErrorCode } from '../../domain/shared/error-catalog.ts';

interface GermanError { summary: string; hint: string }
const claudeDefinitionHint = 'Korrigieren Sie das in der Meldung genannte Feld und führen Sie den Befehl erneut aus.';
const argumentsHint = 'Korrigieren Sie die in der Meldung genannten Argumente; die Verwendung zeigt help <command>.';
const regenerateHint = 'Führen Sie denselben Befehl mit --plan aus, prüfen Sie die Änderungen und generieren Sie dann neu.';

/** German summaries and next steps for every built-in code; original diagnostics remain in error.details.localization. */
export const germanErrors = {
  // Argumente, Optionen und Eingaben
  UNKNOWN_COMMAND: { summary: 'Der Befehl ist nicht registriert.', hint: 'Verfügbare Befehle, auch aktivierte Plugin-Befehle, zeigen help oder schema.' },
  UNKNOWN_OPTION: { summary: 'Dieser Befehl akzeptiert die Option nicht.', hint: 'Die Optionen des Befehls zeigt help <command>.' },
  MISSING_ARGUMENT: { summary: 'Ein erforderliches Argument oder ein Optionswert fehlt.', hint: argumentsHint },
  INVALID_ARGUMENT: { summary: 'Die Argumente oder Optionswerte sind für diesen Befehl ungültig.', hint: argumentsHint },
  DUPLICATE_OPTION: { summary: 'Eine Option wurde wiederholt oder mit ihrer Verneinung kombiniert.', hint: 'Geben Sie jede Option nur einmal an.' },
  INVALID_INPUT: { summary: 'Die Eingabeoptionen sind ungültig oder widersprüchlich.', hint: 'Verwenden Sie genau eine Eingabequelle und die in der Meldung genannte Optionskombination.' },
  INPUT_REQUIRED: { summary: '--stdin wurde ohne weitergeleitete Eingabe angegeben.', hint: 'Leiten Sie den Inhalt an den Befehl weiter oder verwenden Sie --content oder --from.' },
  INVALID_JSON: { summary: 'Die Eingabe ist kein gültiges JSON.', hint: 'Übergeben Sie einen gültigen JSON-Wert und maskieren Sie ihn für Ihre Shell.' },
  INVALID_ENCODING: { summary: 'Der Inhalt ist in der erforderlichen Kodierung ungültig.', hint: 'Verwenden Sie gültiges UTF-8. Binärinhalte schreiben Sie mit write oder create über --stdin, --from oder --encoding base64; edit und strukturierte Befehle akzeptieren nur UTF-8-Text.' },
  INVALID_LANGUAGE: { summary: 'Die Sprache wird nicht unterstützt.', hint: 'Verwenden Sie --lang en oder --lang de.' },
  INVALID_NAME: { summary: 'Der Name entspricht nicht der erforderlichen Namensregel.', hint: 'Verwenden Sie das in der Meldung beschriebene Format, zum Beispiel PascalCase.' },
  INVALID_KEY: { summary: 'Der Eigenschaftsschlüssel ist reserviert oder unsicher.', hint: 'Verwenden Sie einen anderen Eigenschaftsschlüssel.' },
  INVALID_RESULT: { summary: 'Der Befehl lieferte Daten, die nicht als JSON serialisierbar sind.', hint: 'Prüfen Sie bestätigte Tresor-Ereignisse und lesen Sie betroffene Dateien erneut, bevor Sie es wieder versuchen; melden Sie den fehlerhaften Plugin-Befehl.' },
  OPERATION_FAILED: { summary: 'Ein unerwarteter Laufzeit- oder E/A-Fehler ist aufgetreten.', hint: 'Lesen Sie die ursprüngliche Diagnose, prüfen Sie den Arbeitsbereich und lesen Sie betroffene Dateien vor einem erneuten Versuch.' },
  // Pfade, Dateien und geschützte Schreibvorgänge
  INVALID_PATH: { summary: 'Der Pfad ist kein gültiger relativer Pfad im Arbeitsbereich.', hint: 'Verwenden Sie einen relativen Pfad im ausgewählten Arbeitsbereich oder Projekt mit Schrägstrichen und ohne ..-Segmente.' },
  UNSAFE_PATH: { summary: 'Der Pfad verlässt den Arbeitsbereich oder durchquert eine symbolische Verknüpfung.', hint: 'Verwenden Sie einen Pfad innerhalb des Arbeitsbereichs ohne symbolische Verknüpfungen.' },
  NOT_FOUND: { summary: 'Die Datei oder Ressource wurde nicht gefunden.', hint: 'Prüfen Sie Pfad und ausgewähltes Projekt (project current); list zeigt vorhandene Dateien.' },
  CONFLICT: { summary: 'Die Datei existiert bereits oder ihre Revision hat sich seit dem Lesen geändert.', hint: 'Lesen Sie die Datei erneut, gleichen Sie Ihre Änderung mit dem aktuellen Inhalt ab (error.details.currentRevision) und versuchen Sie es dann mit dem Revisionsschutz des Befehls erneut (--if-match oder --revisions-from); create legt nur neue Pfade an.' },
  NO_MATCH: { summary: 'Der --find-Text kommt in der Datei nicht vor.', hint: 'Lesen Sie die Datei erneut und übernehmen Sie den exakten aktuellen Text einschließlich Leerraum und Zeilenenden in --find.' },
  AMBIGUOUS_EDIT: { summary: 'Der --find-Text kommt mehrfach vor; überlappende Treffer zählen mit.', hint: 'Erweitern Sie --find um umgebenden Text, bis er genau einmal passt; error.details.lines nennt die Trefferzeilen.' },
  UNSUPPORTED_EDIT: { summary: 'Diese Bearbeitung wird für den Dateityp nicht unterstützt.', hint: 'Verwenden Sie edit für Markdown und Text, properties für Frontmatter, patch für Canvas und Bases und write für Anhänge.' },
  INVALID_PLAN: { summary: 'Der Schreibvorgang enthält doppelte oder überlappende Pfade.', hint: 'Schreiben Sie jeden Pfad nur einmal und keine Datei dort, wo ein anderer Schreibvorgang ein Verzeichnis braucht.' },
  WORKSPACE_BUSY: { summary: 'Ein anderer Forge-Schreibvorgang hält die Sperre .agent-cli.lock; Forge entfernt sie nie automatisch.', hint: 'Warten Sie und versuchen Sie es erneut. Meldet error.details.stale "likely" (gleicher Rechner, PID-Namensraum und Systemstart; die Prozess-ID läuft nicht mehr), prüfen Sie die Änderungen des Halters, stellen Sie sicher, dass kein Forge-Schreibvorgang läuft, und löschen Sie dann die Sperrdatei. Bei "unknown" prüfen Sie den Halter in error.details.lock zuerst selbst.' },
  DESTINATION_EXISTS: { summary: 'Das Ziel des Verschiebens oder Umbenennens existiert bereits.', hint: 'Wählen Sie ein Ziel, das nicht existiert (error.details.path), oder verschieben bzw. löschen Sie die vorhandene Datei zuerst; Forge überschreibt nie ein Ziel.' },
  PROTECTED_PATH: { summary: 'Der Pfad ist vor Verschieben und Löschen geschützt.', hint: 'Forge verschiebt oder löscht niemals .obsidian, .forge oder im Workspace-Bereich bin (in beliebiger Groß- und Kleinschreibung) und keinen Ordner mit einem .git-Repository; endgültig löscht es nur Ordner ohne symbolische Links, node_modules oder Spezialdateien, verschieben Sie einen solchen Ordner daher in den Papierkorb. Die Bereichswurzel und .git-Pfade werden als INVALID_PATH abgelehnt.' },
  INVALID_MOVE: { summary: 'Das Verschieben oder Umbenennen ist nicht möglich.', hint: 'Verwenden Sie ein Ziel, das sich von der Quelle unterscheidet und nicht in ihr liegt; rename erwartet einen neuen Namen ohne Schrägstriche.' },
  HAS_BACKLINKS: { summary: 'Andere Notizen verlinken noch auf die Datei oder den Ordner.', hint: 'Passen Sie zuerst die Links in error.details.backlinks an oder entfernen Sie sie, verschieben Sie die Datei stattdessen oder löschen Sie mit --allow-broken-links trotzdem.' },
  ROLLBACK_FAILED: { summary: 'Ein fehlgeschlagener Schreibvorgang konnte nicht alle Dateien wiederherstellen.', hint: 'Prüfen und reparieren Sie die in der Meldung genannten Dateien vor einem erneuten Versuch.' },
  // Dokumente
  INVALID_FRONTMATTER: { summary: 'Das YAML-Frontmatter ist ungültig.', hint: 'Korrigieren Sie das Frontmatter zu einer YAML-Zuordnung und prüfen Sie die Notiz mit validate.' },
  INVALID_YAML: { summary: 'Das YAML-Dokument ist ungültig.', hint: 'Korrigieren Sie die in der Meldung genannte Syntax, Schlüssel oder Aliase.' },
  INVALID_CANVAS: { summary: 'Die Canvas-Struktur ist ungültig.', hint: 'Korrigieren Sie die genannten Knoten, Kanten oder IDs; prüfen Sie mit validate <file.canvas>.' },
  INVALID_BASE: { summary: 'Die Base-Struktur ist ungültig.', hint: 'Korrigieren Sie die genannte Base-Definition; prüfen Sie mit validate <file.base>.' },
  INVALID_POINTER: { summary: 'Der JSON Pointer ist ungültig oder verweist auf keine gültige Position.', hint: 'Lesen Sie das Dokument und verwenden Sie einen vorhandenen Pointer-Pfad; /- hängt nur an ein vorhandenes Array an.' },
  // Bases-Abfragen
  INVALID_BASE_QUERY: { summary: 'Die Bases-Abfrage ist ungültig.', hint: 'Prüfen Sie die in der Meldung genannte Ansicht, den Kontext und die Ausdrücke.' },
  INVALID_BASE_EXPRESSION: { summary: 'Ein Bases-Ausdruck kann nicht geparst werden.', hint: 'Korrigieren Sie den in der Meldung genannten Ausdruck.' },
  BASE_EVALUATION_ERROR: { summary: 'Ein Bases-Ausdruck ist bei der Auswertung einer Datei fehlgeschlagen.', hint: 'Prüfen Sie die in der Meldung genannte Ansicht, Datei und den Ausdruck.' },
  BASE_VIEW_NOT_FOUND: { summary: 'Die angeforderte Bases-Ansicht existiert nicht.', hint: 'Führen Sie bases inspect <file.base> aus und übergeben Sie eine vorhandene --view.' },
  BASE_CONTEXT_NOT_FOUND: { summary: 'Die Kontextdatei ist keine indexierte Tresordatei.', hint: 'Übergeben Sie eine vorhandene Tresordatei an --context.' },
  INVALID_BASE_PROPERTY_TYPES: { summary: 'Das Register der Obsidian-Eigenschaftstypen ist ungültig.', hint: 'Korrigieren Sie .obsidian/types.json zu einem JSON-Objekt mit Eigenschaftstypen.' },
  UNSUPPORTED_BASE_PROPERTY_TYPE: { summary: 'Ein Obsidian-Eigenschaftstyp wird nicht unterstützt.', hint: 'Verwenden Sie in .obsidian/types.json einen unterstützten Typ.' },
  // Konfiguration, Installation und Projekte
  INVALID_CONFIG: { summary: 'Die Konfiguration ist ungültig oder nicht lesbar.', hint: 'Korrigieren Sie bin/config.json an der in der Meldung genannten Stelle und prüfen Sie mit config.' },
  INVALID_SETUP: { summary: 'Die Installation kann mit den aktuellen Distributionsdateien nicht abgeschlossen werden.', hint: 'Reparieren Sie den in der Meldung genannten bin-Pfad und führen Sie setup erneut aus.' },
  INVALID_PROJECT: { summary: 'Die Projektmetadaten sind ungültig.', hint: 'Korrigieren Sie .forge/project.json im Projektverzeichnis.' },
  INVALID_PROJECT_NAME: { summary: 'Der Projektname ist ungültig.', hint: 'Verwenden Sie einen kleingeschriebenen Kebab-Case-Namen, zum Beispiel billing-service.' },
  INVALID_PROJECT_CONTEXT: { summary: 'Die gespeicherte Projektauswahl ist ungültig.', hint: 'Verwenden Sie project open <name> oder project close.' },
  INVALID_COMPONENT_KIND: { summary: 'Der Komponententyp ist ungültig.', hint: 'Verwenden Sie domain oder application.' },
  PROJECT_EXISTS: { summary: 'Das Projekt existiert bereits.', hint: 'Wählen Sie einen anderen Namen oder öffnen Sie es mit project open <name>.' },
  PROJECT_NOT_FOUND: { summary: 'Das Projekt existiert nicht.', hint: 'Führen Sie project list aus und öffnen Sie ein vorhandenes Projekt.' },
  PROJECT_REQUIRED: { summary: 'Dieser Befehl benötigt ein ausgewähltes Projekt.', hint: 'Öffnen Sie zuerst mit project open <name> ein Projekt.' },
  STALE_PROJECT_CONTEXT: { summary: 'Das ausgewählte Projekt fehlt oder stimmt nicht mehr mit der Konfiguration überein.', hint: 'Wählen Sie mit project open <name> ein gültiges Projekt oder verwenden Sie project close.' },
  // Vorlagen und Generierung
  INVALID_TEMPLATE: { summary: 'Die Markdown-Vorlage ist ungültig.', hint: 'Korrigieren Sie das in der Meldung genannte Frontmatter oder die Platzhalter.' },
  INVALID_TEMPLATE_DATE: { summary: 'Ein Datum oder Datumsformat der Vorlage ist ungültig.', hint: 'Verwenden Sie ein ISO-Datum und ein unterstütztes Datumsformat.' },
  INVALID_TEMPLATE_PACK: { summary: 'Das Vorlagenpaket ist ungültig.', hint: 'Verwenden Sie eindeutige Vorlagen-IDs und Zielpfade.' },
  INVALID_TEMPLATE_VALUES: { summary: 'Vorlagenwerte fehlen oder haben den falschen Typ.', hint: 'Führen Sie templates inspect <template.md> aus und geben Sie die Pflichtwerte an.' },
  UNKNOWN_TEMPLATE_VARIABLE: { summary: 'Die Vorlage verwendet eine nicht deklarierte Variable.', hint: 'Deklarieren Sie die Variable oder entfernen Sie den Platzhalter; prüfen Sie mit templates inspect <template.md>.' },
  UNKNOWN_GENERATOR: { summary: 'Der Generator ist nicht registriert.', hint: 'Verfügbare Generatoren zeigt make.' },
  INVALID_GENERATION_PLAN: { summary: 'Der Generierungsplan hat überlappende Ausgaben oder ungültige Optionen.', hint: 'Verwenden Sie getrennte Ausgabe- und Manifestpfade und kombinieren Sie die Planung nicht mit --revisions-from.' },
  INVALID_GENERATION_REVISIONS: { summary: 'Die Revisionsfreigabe passt nicht zum geprüften Plan.', hint: 'Erstellen Sie mit --plan-out einen neuen Plan und übergeben Sie diese Datei an --revisions-from.' },
  UI_DRIFT: { summary: 'Generierte UI-Dateien fehlen oder weichen von den Definitionen ab.', hint: regenerateHint },
  DATA_SOURCE_DRIFT: { summary: 'Generierte Datenquellendateien fehlen oder weichen von den Definitionen ab.', hint: regenerateHint },
  GENERATION_DRIFT: { summary: 'Generierte Dateien fehlen oder weichen von der Ausgabe des Generators ab.', hint: 'Führen Sie denselben make-Befehl mit --plan aus, prüfen Sie die Änderungen und generieren Sie dann neu.' },
  // Projekt-Workflows
  INVALID_WORKFLOW: { summary: 'Ein Projekt-Workflow ist ungültig, oder zwei Workflows erzeugen dieselbe Datei.', hint: 'Korrigieren oder benennen Sie den in der Meldung genannten Workflow unter src/infrastructure/workflows/<concern>/ um und führen Sie dann workflows sync aus.' },
  WORKFLOW_DRIFT: { summary: 'Generierte GitHub-Workflows fehlen, weichen ab oder sind veraltet.', hint: 'Führen Sie workflows sync aus, prüfen Sie die Änderungen in .github/workflows und committen Sie sie zusammen mit ihren Quellen.' },
  // UI, Interaktionen und Datenquellen
  INVALID_UI: { summary: 'Eine Komponentendefinition ist ungültig.', hint: 'Korrigieren Sie die genannte Definition; prüfen Sie mit components validate.' },
  INVALID_UI_LIBRARY: { summary: 'Die Komponentenbibliothek ist ungültig.', hint: 'Führen Sie components validate aus und korrigieren Sie die gemeldeten Definitionen.' },
  INVALID_UI_FRAMEWORK: { summary: 'Das UI-Ziel wird nicht unterstützt.', hint: 'Verwenden Sie html, htmx, vanilla, vue, svelte, react oder angular.' },
  EMPTY_UI_LIBRARY: { summary: 'Die Komponentenbibliothek enthält keine Definitionen.', hint: 'Führen Sie components init aus oder fügen Sie eine Markdown-Definition hinzu.' },
  DUPLICATE_UI_COMPONENT: { summary: 'Zwei Komponentendefinitionen haben dieselbe ID.', hint: 'Vergeben Sie für jede Komponente eine eindeutige ID.' },
  UNKNOWN_UI_COMPONENT: { summary: 'Die Komponente ist nicht definiert.', hint: 'Führen Sie components list aus und verwenden Sie eine vorhandene ID.' },
  CYCLIC_UI_COMPONENT: { summary: 'Die Komponentenreferenzen bilden einen Zyklus.', hint: 'Entfernen Sie die in der Meldung genannte zyklische Referenz.' },
  UI_RENDERER_UNAVAILABLE: { summary: 'Für dieses UI-Ziel ist kein Generator verfügbar.', hint: 'Wählen Sie ein unterstütztes --framework.' },
  INVALID_INTERACTION: { summary: 'Eine Interaktionsdefinition ist ungültig.', hint: 'Korrigieren Sie das genannte Ereignis, die Aktionen oder Bindungen; prüfen Sie mit interactions validate.' },
  DUPLICATE_INTERACTION: { summary: 'Zwei Interaktionsdefinitionen haben dieselbe ID.', hint: 'Vergeben Sie für jede Interaktion eine eindeutige ID.' },
  EMPTY_INTERACTION_LIBRARY: { summary: 'Die Interaktionsbibliothek enthält keine Definitionen.', hint: 'Führen Sie interactions init aus oder fügen Sie eine Markdown-Definition hinzu.' },
  UNKNOWN_INTERACTION: { summary: 'Die Interaktion ist nicht definiert.', hint: 'Führen Sie interactions list aus und prüfen Sie die Interaktionsreferenzen der Komponente.' },
  INVALID_DATA_SOURCE: { summary: 'Eine Datenquellendefinition ist ungültig.', hint: 'Korrigieren Sie die genannten Felder; prüfen Sie mit data-sources validate.' },
  DUPLICATE_DATA_SOURCE: { summary: 'Zwei Datenquellendefinitionen haben dieselbe ID.', hint: 'Vergeben Sie für jede Datenquelle eine eindeutige ID.' },
  EMPTY_DATA_SOURCE_LIBRARY: { summary: 'Die Datenquellenbibliothek enthält keine Definitionen.', hint: 'Führen Sie data-sources init aus oder fügen Sie eine Markdown-Definition hinzu.' },
  UNKNOWN_DATA_SOURCE: { summary: 'Die Datenquelle ist nicht definiert.', hint: 'Führen Sie data-sources list aus und verwenden Sie eine vorhandene ID.' },
  DATA_SOURCE_RENDERER_UNAVAILABLE: { summary: 'Für diese Datenquelle ist kein Generator verfügbar.', hint: 'Verwenden Sie eine unterstützte Datenquellenart; Hinweise zur Generierung zeigt help make.' },
  // Plugins, Skills und Ereignisse
  INVALID_PLUGIN: { summary: 'Ein Plugin-Manifest oder eine Plugin-Implementierung ist ungültig.', hint: 'Korrigieren Sie das genannte Plugin oder deaktivieren Sie Plugins mit --no-plugins.' },
  INVALID_PLUGIN_CONFIG: { summary: 'Die Plugin-Konfiguration ist ungültig.', hint: 'Tragen Sie in bin/config.json unter plugins.enabled eindeutige Kebab-Case-IDs installierter Benutzer-Plugins ein; plugins listet sie auf.' },
  INCOMPATIBLE_PLUGIN: { summary: 'Das Plugin benötigt eine neuere Forge-Version.', hint: 'Aktualisieren Sie The Forge oder deaktivieren Sie das Plugin.' },
  DUPLICATE_PLUGIN: { summary: 'Das Plugin ist doppelt registriert.', hint: 'Aktivieren Sie jedes Plugin nur einmal.' },
  PLUGIN_NAMESPACE: { summary: 'Eine Plugin-ID oder ein Plugin-Beitrag liegt außerhalb seines Namensraums.', hint: 'Stellen Sie Befehls-, Generator-, Skill- und Ereignis-IDs eines Benutzer-Plugins sowie den Dienst-IDs jedes Plugins die Plugin-ID und einen Punkt und Fehlercodes seine ID in UPPER_SNAKE_CASE voran; verwenden Sie keinen Host-Ereignisnamensraum (command, operation, vault, metadataCache, workspace, plugin) als Plugin-ID beanspruchen Sie core: true nicht außerhalb des Bundles und deklarieren Sie an einem Generator keine Optionen, die make gehören (out, plan, plan-out, check, revisions-from).' },
  PLUGIN_SERVICE_MISSING: { summary: 'Ein Plugin benötigt einen Dienst, den kein aktiviertes Plugin bereitstellt, oder verwendet einen nicht deklarierten Dienst.', hint: 'Aktivieren Sie das Plugin, das den in error.details.service genannten Dienst bereitstellt (plugins zeigt die Anbieter), oder deklarieren Sie ihn in requires des Plugins.' },
  PLUGIN_UNAVAILABLE: { summary: 'Der Befehl oder Generator gehört zu einem Plugin, das in diesem Aufruf nicht verfügbar ist.', hint: 'error.details.reason nennt den Grund: Beheben Sie die in error.details.issues aufgeführten Probleme in plugins.settings in bin/config.json oder aktivieren Sie den genannten deaktivierten Anbieter (entfernen Sie ihn aus plugins.disabled) und wiederholen Sie den Befehl. plugins zeigt Zustand und Grund jedes Plugins.' },
  PLUGIN_SERVICE_CYCLE: { summary: 'Die Dienstabhängigkeiten der Plugins bilden einen Zyklus.', hint: 'Lösen Sie den in error.details.plugins genannten Zyklus auf, sodass ein Plugin keinen Dienst des anderen mehr benötigt.' },
  PLUGIN_LIFECYCLE: { summary: 'Ein Plugin hat den Host außerhalb seines Lebenszyklus verwendet.', hint: 'Registrieren Sie Beiträge vor der Aktivierung und verwenden Sie den Host nach der Freigabe nicht mehr.' },
  DUPLICATE_OR_INVALID_ID: { summary: 'Eine Beitrags-ID ist ungültig oder bereits registriert.', hint: 'Verwenden Sie eine eindeutige, kleingeschriebene ID mit Punkten.' },
  UNKNOWN_SKILL: { summary: 'Der Skill ist nicht registriert.', hint: 'Verfügbare Skills zeigt skills list.' },
  INVALID_EVENT: { summary: 'Eine Ereignisdefinition oder der Ereigniszustand ist ungültig.', hint: 'Definieren Sie Ereignisse vor der Freigabe mit einer ID mit Punkten und einem Validator.' },
  INVALID_EVENT_LISTENER: { summary: 'Ein Ereignisbehandler ist keine Funktion.', hint: 'Übergeben Sie eine Funktion als Behandler.' },
  INVALID_EVENT_PAYLOAD: { summary: 'Die Ereignisdaten entsprechen nicht dem Ereignisvertrag.', hint: 'Prüfen Sie den Vertrag mit events und senden Sie passende Daten.' },
  DUPLICATE_EVENT: { summary: 'Die Ereignis-ID ist bereits registriert.', hint: 'Verwenden Sie eine eindeutige Ereignis-ID.' },
  UNKNOWN_EVENT: { summary: 'Das Ereignis ist nicht registriert.', hint: 'Registrierte Ereignis-IDs zeigt events.' },
  EVENT_RECURSION: { summary: 'Ereignisbehandler haben die maximale Rekursionstiefe überschritten.', hint: 'Verhindern Sie, dass Behandler die Ereignisse auslösen, die sie selbst aufrufen.' },
  EVENT_OWNERSHIP: { summary: 'Ein Plugin wollte ein Ereignis senden, das ihm nicht gehört.', hint: 'Senden Sie nur Ereignisse im Namensraum Ihres Plugins; Host-Ereignisse (vault.*, metadataCache.*, workspace.*, operation.*, command.*, plugin.*) sendet der Host, die Ereignisse eines anderen Plugins dieses Plugin.' },
  // Claude-Code-Definitionen
  INVALID_CLAUDE_AGENT: { summary: 'Die Claude-Agentendefinition ist ungültig.', hint: claudeDefinitionHint },
  INVALID_CLAUDE_HOOKS: { summary: 'Die Claude-Hook-Konfiguration ist ungültig.', hint: claudeDefinitionHint },
  INVALID_CLAUDE_PLUGIN: { summary: 'Das Claude-Plugin-Manifest oder eine Plugin-Datei ist ungültig.', hint: claudeDefinitionHint },
  INVALID_CLAUDE_SETTINGS: { summary: 'Die Claude-Einstellungsdatei ist ungültig.', hint: 'Korrigieren Sie die JSON-Struktur der in der Meldung genannten Einstellungsdatei.' },
  INVALID_CLAUDE_COMMAND: { summary: 'Dieser Claude-Befehl wird nicht unterstützt.', hint: 'Unterstützte Befehle zeigt claude capabilities.' },
  INVALID_CLAUDE_ARGUMENT: { summary: 'Ein Argument des Claude-Befehls ist ungültig.', hint: argumentsHint },
  INVALID_CLAUDE_OPTION: { summary: 'Diese Option ist für den Claude-Befehl nicht zulässig.', hint: 'Prüfen Sie help claude und entfernen Sie die Option.' },
  INVALID_CLAUDE_SCOPE: { summary: 'Der Claude-Geltungsbereich ist ungültig.', hint: 'Prüfen Sie help claude und übergeben Sie einen für diese Aktion unterstützten --scope.' },
  INVALID_CLAUDE_INPUT: { summary: 'Die Claude-Eingabe ist ungültig oder zu groß.', hint: 'Übergeben Sie gültige Eingaben innerhalb des Größenlimits.' },
  INVALID_CLAUDE_OUTPUT: { summary: 'Das Claude-Ausgabeformat ist ungültig.', hint: 'Verwenden Sie text, json oder json-last-line.' },
  INVALID_CLAUDE_OUTPUT_LIMIT: { summary: 'Das Claude-Ausgabelimit ist ungültig.', hint: 'Verwenden Sie eine positive ganze Zahl von Bytes.' },
  INVALID_CLAUDE_TIMEOUT: { summary: 'Das Claude-Zeitlimit ist ungültig.', hint: 'Geben Sie das Zeitlimit in Millisekunden innerhalb des in der Meldung genannten Bereichs an.' },
  INVALID_CLAUDE_EXECUTABLE: { summary: 'Der Pfad zur Claude-Code-CLI ist ungültig.', hint: 'Übergeben Sie einen ausführbaren Pfad an --claude-bin.' },
  // Claude-Code-Prozess
  CLAUDE_NOT_INSTALLED: { summary: 'Die Claude-Code-CLI wurde nicht gefunden.', hint: 'Installieren Sie Claude Code und nehmen Sie claude in PATH auf oder verwenden Sie --claude-bin.' },
  CLAUDE_WORKING_DIRECTORY_UNAVAILABLE: { summary: 'Das Arbeitsverzeichnis für Claude Code ist nicht verfügbar.', hint: 'Prüfen Sie, dass das ausgewählte Projekt oder der Arbeitsbereich existiert und ein Verzeichnis ist.' },
  CLAUDE_COMMAND_FAILED: { summary: 'Claude Code konnte nicht gestartet werden oder wurde unerwartet beendet.', hint: 'Lesen Sie error.details, prüfen Sie den externen Zustand und wiederholen Sie dann bewusst.' },
  CLAUDE_COMMAND_TIMEOUT: { summary: 'Der Claude-Befehl hat sein Zeitlimit überschritten.', hint: 'Prüfen Sie den externen Zustand; wiederholen Sie mit größerem --timeout nur, wenn die Arbeit nicht abgeschlossen wurde.' },
  CLAUDE_OUTPUT_LIMIT: { summary: 'Die Claude-Ausgabe hat das Größenlimit überschritten.', hint: 'Prüfen Sie den externen Zustand; wiederholen Sie nur bei Bedarf mit größerem Ausgabelimit.' },
  CLAUDE_COMMAND_INTERRUPTED: { summary: 'Der Claude-Befehl wurde durch ein Signal unterbrochen (Exit 130 bei SIGINT, 143 bei SIGTERM).', hint: 'Prüfen Sie den externen Zustand, bevor Sie den Befehl erneut ausführen.' },
  CLAUDE_RUNTIME_FAILED: { summary: 'Claude Code wurde mit einem Status ungleich null beendet.', hint: 'Prüfen Sie error.details (nativer Status, Ausgabe und geparstes Ergebnis) und den externen Zustand vor einer Wiederholung.' },
  CLAUDE_INVALID_OUTPUT: { summary: 'Claude Code war erfolgreich, lieferte aber nicht das angeforderte JSON.', hint: 'Prüfen Sie stdout und den externen Zustand vor einer Wiederholung.' },
} satisfies Record<ErrorCode, GermanError>;
