import { ensure } from '../shared/errors.ts';
import { vaultPath } from '../documents/file.ts';

/** Projects author CI under this project-relative directory, one folder per concern. */
const workflowSourceDirectory = 'src/infrastructure/workflows';
/** Generated entrypoints live at the workspace root, where GitHub discovers them. */
export const generatedWorkflowDirectory = '.github/workflows';
/** The first line of every generated file; it marks the file as owned by `workflows sync`. */
const generatedMarker = '# Generated by forge workflows sync from ';
/** Synced workflows receive the project's workspace-relative path in this workflow-level variable. */
export const projectPathVariable = 'FORGE_PROJECT_PATH';

export interface WorkflowSource {
  project: string;
  /** Workspace-relative project directory, for example src/the-forge. */
  projectDirectory: string;
  concern: string;
  /** Workspace-relative authored file. */
  source: string;
  /** Workspace-relative generated entrypoint. */
  target: string;
}

const segment = /^[a-z0-9][a-z0-9._-]*$/;

/** Match `<project>/src/infrastructure/workflows/<concern>/<file>.yml|yaml`; deeper files are not workflows. */
export function workflowSource(project: string, projectDirectory: string, path: string): WorkflowSource | undefined {
  const prefix = `${projectDirectory}/${workflowSourceDirectory}/`;
  if (!path.startsWith(prefix)) return undefined;
  const parts = path.slice(prefix.length).split('/');
  if (parts.length !== 2) return undefined;
  const [concern, file] = parts as [string, string];
  const match = /^(.+)\.ya?ml$/i.exec(file);
  if (!match) return undefined;
  const stem = match[1]!;
  ensure(segment.test(concern) && segment.test(stem), 'INVALID_WORKFLOW', `Workflow concern and file names must be lowercase kebab-case: ${path}.`);
  return { project, projectDirectory, concern, source: path, target: generatedWorkflowPath(project, concern, stem) };
}

/** `<project>--<concern>.yml`, or `<project>--<concern>--<stem>.yml` when the file is not named after its concern. */
export function generatedWorkflowPath(project: string, concern: string, stem: string): string {
  return `${generatedWorkflowDirectory}/${project}--${concern}${stem === concern ? '' : `--${stem}`}.yml`;
}

export function generatedHeader(source: string): string {
  return `${generatedMarker}${source}.\n# Do not edit this file; change the source and run: node bin/forge.js workflows sync\n`;
}

export function isGeneratedWorkflow(text: string): boolean {
  return text.startsWith(generatedMarker);
}

/**
 * Join an authored POSIX path onto the project directory. A leading `/` marks a workspace-relative
 * path instead; `.` and `..` segments are resolved and must stay inside the workspace.
 */
export function projectRelative(path: string, projectDirectory: string): string {
  const workspace = path.startsWith('/');
  const parts: string[] = workspace ? [] : projectDirectory.split('/');
  for (const part of (workspace ? path.slice(1) : path).split('/')) {
    if (part === '' || part === '.') continue;
    if (part === '..') {
      ensure(parts.length > 0, 'INVALID_WORKFLOW', `Workflow path leaves the workspace: ${path}.`);
      parts.pop();
    } else parts.push(part);
  }
  return parts.length ? parts.join('/') : '.';
}

/** Path filters keep their `!` negation; `/**` style workspace patterns are anchored at the root. */
export function scopedPattern(pattern: string, projectDirectory: string): string {
  const negated = pattern.startsWith('!');
  const body = negated ? pattern.slice(1) : pattern;
  ensure(body.length > 0, 'INVALID_WORKFLOW', 'Workflow path filters must not be empty.');
  const scoped = body.startsWith('/') ? body.slice(1) : `${projectDirectory}/${body}`;
  return `${negated ? '!' : ''}${scoped || '**'}`;
}

export interface TriggerFilters { paths?: readonly string[]; pathsIgnore?: readonly string[] }

/**
 * A push or pull_request trigger runs for the project's files and its own generated entrypoint.
 * Declared `paths` are scoped; `paths-ignore` becomes negated paths after the project pattern,
 * because GitHub rejects both filters on one event.
 */
export function scopedTriggerPaths(filters: TriggerFilters, projectDirectory: string, target: string): string[] {
  const scope = (pattern: string) => scopedPattern(pattern, projectDirectory);
  const paths = filters.paths !== undefined
    ? filters.paths.map(scope)
    : [`${projectDirectory}/**`, ...(filters.pathsIgnore ?? []).map(pattern => scope(pattern.startsWith('!') ? pattern.slice(1) : `!${pattern}`))];
  return [...new Set([...paths, target])];
}

/** Every generated target must be unique and contained; distinct sources may not share an entrypoint. */
export function ensureDistinctTargets(sources: readonly WorkflowSource[]): void {
  const seen = new Map<string, string>();
  for (const source of sources) {
    vaultPath(source.target);
    const previous = seen.get(source.target);
    ensure(previous === undefined, 'INVALID_WORKFLOW', `Workflow sources ${previous} and ${source.source} both generate ${source.target}; rename one.`);
    seen.set(source.target, source.source);
  }
}
