import { AppError, ensure, forgeError } from '../../domain/shared/errors.ts';
import type { WriteRequest } from '../../domain/documents/file.ts';
import {
  ensureDistinctTargets, generatedWorkflowDirectory, isGeneratedWorkflow, workflowSource, type WorkflowSource,
} from '../../domain/workflows/workflow.ts';
import type { ProjectInfo } from '../projects/projects.ts';
import type { Workspace } from '../workspace/workspace.ts';

/** Renders one authored workflow as its generated, project-scoped entrypoint. */
export interface WorkflowRenderer {
  render(bytes: Uint8Array, source: WorkflowSource): Uint8Array;
}
export interface WorkflowProjects {
  list(): Promise<ProjectInfo[]>;
}
type WorkflowStatus = 'missing' | 'changed' | 'unchanged' | 'stale';
interface WorkflowEntry {
  project: string | null;
  concern: string | null;
  source: string | null;
  target: string;
  status: WorkflowStatus;
}
interface PlannedWorkflow extends WorkflowEntry { bytes?: Uint8Array; revision?: string }

const equalBytes = (left: Uint8Array, right: Uint8Array) => left.length === right.length && left.every((byte, index) => byte === right[index]);
const decode = (bytes: Uint8Array) => new TextDecoder().decode(bytes);
const byTarget = (left: { target: string }, right: { target: string }) => left.target < right.target ? -1 : left.target > right.target ? 1 : 0;

/**
 * Authored project workflows are the single source of truth. Sync writes their generated copies into the
 * workspace's GitHub workflow directory through the guarded workspace, and removes generated copies whose
 * source disappeared. Files without the generated marker are never overwritten or removed.
 */
export class WorkflowSync {
  constructor(private readonly workspace: Workspace, private readonly projects: WorkflowProjects, private readonly renderer: WorkflowRenderer) {}

  async list() {
    const workflows = (await this.plan()).map(entry => this.entry(entry));
    return { directory: generatedWorkflowDirectory, count: workflows.length, inSync: workflows.every(entry => entry.status === 'unchanged'), workflows };
  }

  async check() {
    const workflows = (await this.plan()).map(entry => this.entry(entry));
    const drift = workflows.filter(entry => entry.status !== 'unchanged');
    if (drift.length) {
      throw forgeError('WORKFLOW_DRIFT', `Generated workflows differ from their sources: ${drift.map(entry => `${entry.target} (${entry.status})`).join(', ')}. Run workflows sync.`, { workflows: drift });
    }
    return { check: true, inSync: true, count: workflows.length, workflows };
  }

  async sync() {
    const plan = await this.plan();
    const writes: WriteRequest[] = plan.filter(entry => entry.status === 'missing' || entry.status === 'changed')
      .map(entry => ({ path: entry.target, bytes: entry.bytes!, ...(entry.revision ? { expectedRevision: entry.revision } : {}) }));
    const changes = writes.length ? (await this.workspace.write(writes, { diff: true })).changes : [];
    for (const stale of plan.filter(entry => entry.status === 'stale')) {
      changes.push(...(await this.workspace.remove(stale.target, stale.revision!)).changes);
    }
    return { dryRun: this.workspace.dryRun, workflows: plan.map(entry => this.entry(entry)), changes };
  }

  private entry({ project, concern, source, target, status }: PlannedWorkflow): WorkflowEntry {
    return { project, concern, source, target, status };
  }

  private async plan(): Promise<PlannedWorkflow[]> {
    const paths = await this.workspace.files.list();
    const sources: WorkflowSource[] = [];
    for (const project of await this.projects.list()) {
      for (const path of paths) {
        const source = workflowSource(project.name, project.directory, path);
        if (source) sources.push(source);
      }
    }
    ensureDistinctTargets(sources);
    const desired = new Set(sources.map(source => source.target));
    const planned = await Promise.all(sources.map(async (source): Promise<PlannedWorkflow> => {
      const bytes = this.renderer.render((await this.workspace.files.read(source.source)).bytes, source);
      const current = await this.current(source.target);
      ensure(current === undefined || isGeneratedWorkflow(decode(current.bytes)), 'CONFLICT', `${source.target} exists but was not generated by workflows sync. Move or delete it, then run workflows sync.`, { path: source.target });
      const status = current === undefined ? 'missing' : equalBytes(current.bytes, bytes) ? 'unchanged' : 'changed';
      return { project: source.project, concern: source.concern, source: source.source, target: source.target, status, bytes, ...(current ? { revision: current.revision } : {}) };
    }));
    const prefix = `${generatedWorkflowDirectory}/`;
    const stale = await Promise.all(paths.filter(path => path.startsWith(prefix) && !path.slice(prefix.length).includes('/') && !desired.has(path)).map(async path => {
      const current = await this.workspace.files.read(path);
      return isGeneratedWorkflow(decode(current.bytes))
        ? [{ project: null, concern: null, source: null, target: path, status: 'stale' as const, revision: current.revision }]
        : [];
    }));
    return [...planned, ...stale.flat()].sort(byTarget);
  }

  private async current(path: string) {
    try { return await this.workspace.files.read(path); }
    catch (error) {
      if (error instanceof AppError && error.code === 'NOT_FOUND') return undefined;
      throw error;
    }
  }
}
