// Generated by Forge from Markdown. Edit the definition or its Storybook extension module.
import type { Meta as _Meta, StoryObj as _StoryObj } from "@storybook/angular";
import { CardComponent as component } from "../components/card";

const meta = {
  argTypes: {},
  args: {},
  parameters: {
    docs: {
      description: {
        component: "# card\n\nSemantic article boilerplate. Supply child content and application behavior in your project.\n"
      }
    }
  },
  tags: ["autodocs"],
  title: "Components/card",
  component,
} satisfies _Meta<InstanceType<typeof component>>;

export default meta;
type _Story = _StoryObj<InstanceType<typeof component>>;

export const Default: _Story = {
} satisfies _Story;
