// Generated by Forge from Markdown. Edit the definition or its Storybook extension module.
import type { Meta as _Meta, StoryObj as _StoryObj } from "@storybook/angular";
import { TripPlannerComponent as component } from "../components/trip-planner";

const meta = {
  argTypes: {
    heading: {
      control: "text",
      description: "Page heading",
      type: {
        name: "string",
        required: false
      }
    }
  },
  args: {
    heading: "Plan your next trip"
  },
  parameters: {
    docs: {
      description: {
        component: "# Trip planner\n\nThe Trailhead planning page: upcoming [[trip-card]] entries, a trip request form saved with [[save-trip-draft]], live destination capture through [[capture-destination]] and a packing-tips toggle using the starter [[toggle-expanded]] interaction. Implements [[UC-001 Plan a trip]] as designed in [[Trip planner design]].\n"
      }
    },
    layout: "fullscreen"
  },
  tags: ["autodocs"],
  title: "Trailhead/TripPlanner",
  component,
} satisfies _Meta<InstanceType<typeof component>>;

export default meta;
type _Story = _StoryObj<InstanceType<typeof component>>;

export const Default: _Story = {
} satisfies _Story;

export const Weekend: _Story = {
  args: {
    heading: "Plan a weekend away"
  },
} satisfies _Story;
