import { workflowPath } from './code.mjs';
import { uiTargets } from './design-system.mjs';
import { dataOutputs } from './data.mjs';
import { project } from './project.mjs';
import { vaultPaths } from './vault.mjs';

export const buildLogPath = 'docs/Build log.md';

/** @param {string} path */
const link = path => `[${path}](<${path}>)`;

const folders = [
  ['docs/product, docs/use-cases, docs/design, docs/delivery', 'PRD, three use cases, design, build spec, implementation, test and release plans rendered from the workflow templates, then linked with guarded `properties` and `edit` changes', '`templates install workflow`, `make document --template workflow/<kind>.md --date`, `properties --set`, `edit --find/--replace`, `edit --append`'],
  [vaultPaths.hub, 'Hub note that links the whole knowledge graph and embeds a Bases view', '`create`'],
  [vaultPaths.canvas, 'JSON Canvas architecture map with file nodes, groups and labelled edges', '`create`, `patch --pointer /nodes` and `/edges` (replace), `/nodes/-` and `/edges/-` (append), `validate`'],
  ['docs/bases', 'Native Bases views: documents by stage, requirement traceability and library backlinks', '`create`, `validate`, `bases list`, `bases inspect`, `bases query`'],
  ['library/components', 'Starter component library plus the Trailhead `trip-card` and `trip-planner` definitions', '`components init`, `components create`, `write --if-match`, `components validate`'],
  ['library/interactions', 'Starter interactions plus `toggle-favorite`, `capture-destination` and `save-trip-draft`', '`interactions init`, `interactions create`, `write --if-match`, `interactions validate`'],
  ['library/data-sources', 'REST (`trips-api`) and local JSON (`trail-guides`) data-source definitions', '`data-sources create`, `write --if-match`, `data-sources validate`'],
  [`ui/{${uiTargets.join(',')}}`, 'Generated UI components and Storybook CSF stories for all seven targets, checked for drift', '`make ui trip-planner --framework <target> --stories --out ... --stories-out ...`, `make ui ... --check`'],
  ['src/domain, src/application', 'Domain entity, value object and event; application use cases with injected ports', '`project component`, `make entity`, `make value-object`, `make event`, `make use-case`'],
  ['src/presentation/forms', 'Typed Zod forms rendered by the Vite form preview (`npm run dev`)', '`project create`, `make form TripRequest`'],
  [`${dataOutputs.adapters}, ${dataOutputs.fixtures}`, 'Typed adapters and deterministic fixtures generated from the data-source definitions', '`make data-source`, `make data-source --check`'],
  [workflowPath, "The project's own CI workflow: install, check and test from this directory", '`create`'],
  ['tests', 'Generated tests plus authored adapter, model and knowledge-graph tests run by this project\'s Vitest', '`project create`, `project component`, `make form`, `create`'],
  ['.claude/agents', 'Native Claude Code reviewer agent for traceability', '`claude agents create`, `claude agents list`'],
  ['.agents/skills', 'Forge process skills installed into the project', '`skills install`'],
  ['src/index.ts', 'Library public API exporting the Trailhead model, form and adapters', '`write --if-match`'],
  ['package.json, configs, scripts', 'Independent toolchain: structure, Oxlint, fallow, TypeScript, Vite and Vitest. `configs/quality/fallow.json` also ignores `ui/**`, whose framework sources belong to downstream applications', '`project create`, `write --if-match`'],
];

/**
 * @param {{ base: string, view: string, files: string[], total: number }[]} queries
 */
export function readme(queries) {
  const results = queries.map(query => [
    `### ${query.view} (\`${query.base}\`)`,
    '',
    '```sh',
    `node bin/app.js bases query '${query.base}' --view '${query.view}'`,
    '```',
    '',
    `${query.total} matching file${query.total === 1 ? '' : 's'}:`,
    '',
    ...query.files.map(file => `- ${link(file)}`),
    '',
  ].join('\n')).join('\n');
  return `# Trailhead: The Forge showcase

Trailhead is a small fictional trip-planning web app for hiking groups. This managed Forge project shows The Forge's capabilities end to end: an Obsidian-compatible knowledge graph of specs and docs, Canvas and Bases, a component library with interactions generated for all seven UI targets with Storybook stories, data sources with typed adapters and fixtures, domain and application code, forms, a native Claude agent, agent skills and the project's own CI workflow.

Everything here is generated by the bundled CLI. The repository's \`scripts/showcase.mjs\` drives \`node bin/app.js\` with fixed inputs and the fixed date ${project.date}, so regeneration is byte-for-byte reproducible. Do not edit generated files by hand; change the script and regenerate.

## Browse, regenerate and verify

- **Obsidian:** open \`${project.directory}\` as a vault and start at ${link(vaultPaths.hub)}. Opening the whole repository as a vault also works, but Canvas file paths are relative to this project folder.
- **Regenerate** from the repository root: \`npm run showcase\`. **Check drift:** \`npm run showcase:check\` regenerates into a temporary workspace and lists differing paths.
- **Project checks** from this directory: \`npm ci\`, then \`npm run check\` and \`npm test\`. The committed \`package-lock.json\` is refreshed only by \`npm run showcase -- --lockfile\`.
- **Forge commands** run from the repository root. File commands need this project selected (\`node bin/app.js project open ${project.id}\`); restore the checkout's selection afterwards with \`node bin/app.js project open the-forge\`. UI and data-source generation accept \`--project ${project.id}\` without changing the selection.

## What each folder demonstrates

| Path | Demonstrates | Produced by |
| --- | --- | --- |
${folders.map(([path, what, how]) => `| \`${path}\` | ${what} | ${how} |`).join('\n')}

Every command, in order, is recorded in ${link(buildLogPath)}.

## Bases query results

These results were produced by \`bases query\` during generation, with \`${project.id}\` selected and without Obsidian.

${results}`;
}

/** @param {{ section: string, command: string }[]} log */
export function buildLog(log) {
  /** @type {Map<string, string[]>} */
  const sections = new Map();
  for (const entry of log) sections.set(entry.section, [...(sections.get(entry.section) ?? []), entry.command]);
  const body = [...sections].map(([section, commands]) => `## ${section}\n\n\`\`\`sh\n${commands.join('\n')}\n\`\`\`\n`).join('\n');
  return `---
type: log
tags: [trailhead, forge]
hub: "[[Trailhead]]"
---
# Build log

Every Forge CLI invocation the showcase script made to build this project, in order. Long JSON values and Markdown inputs are abbreviated; \`< input\` marks content passed on standard input, and \`<revision>\` the SHA-256 revision read before a guarded change. The script runs these commands in a temporary workspace with \`--root\` and \`--json\`, then copies \`${project.directory}\` into the repository. See [[Trailhead]] for the product hub.

${body}`;
}
