// Generated by Forge from Markdown. Edit the definition or its Storybook extension module.
import type { Meta as _Meta, StoryObj as _StoryObj } from "@storybook/vue3";
import component from "../components/page.vue";

const meta = {
  argTypes: {},
  args: {},
  parameters: {
    docs: {
      description: {
        component: "# page\n\nSemantic div boilerplate. Supply child content and application behavior in your project.\n"
      }
    }
  },
  tags: ["autodocs"],
  title: "Components/page",
  component,
} satisfies _Meta<typeof component>;

export default meta;
type _Story = _StoryObj<typeof meta>;

export const Default: _Story = {
} satisfies _Story;
