// Generated by Forge from Markdown. Edit the definition or its Storybook extension module.
import type { Meta as _Meta, StoryObj as _StoryObj } from "@storybook/react";
import component from "../components/trip-card";

const meta = {
  argTypes: {
    destination: {
      control: "text",
      description: "Primary destination",
      type: {
        name: "string",
        required: false
      }
    },
    nights: {
      control: "number"
    },
    title: {
      control: "text",
      description: "Trip name shown as the card heading",
      type: {
        name: "string",
        required: true
      }
    }
  },
  args: {
    destination: "Lake Tahoe",
    nights: 2,
    title: "Lakeside weekend"
  },
  parameters: {
    docs: {
      description: {
        component: "# Trip card\n\nSummarises one planned trip from the [[trips-api]] data source and lets the hiker mark it as a favourite with [[toggle-favorite]]. Designed in [[Trip planner design]] for REQ-003.\n"
      }
    },
    layout: "centered"
  },
  tags: ["autodocs"],
  title: "Trailhead/TripCard",
  component,
} satisfies _Meta<typeof component>;

export default meta;
type _Story = _StoryObj<typeof meta>;

export const Default: _Story = {
} satisfies _Story;

export const LongTrip: _Story = {
  args: {
    destination: "Sierra Nevada",
    nights: 9,
    title: "Pacific Crest section"
  },
} satisfies _Story;
